"""list-orgs -- discover DSL course and cohort orgs dynamically from GitHub.

Source of truth: every org's `.github` repo is tagged by `bootstrap_course.py` -
`dsl-course-hub` for a persistent COURSE org, `dsl-cohort` for a per-year COHORT
org. This tool searches for both topics across all repos the caller can see, reads
each org's `.github/dsl-course.yml`, and emits a JSON / Markdown / YAML inventory
of the two tiers separately.

Usage:
    python3 -m dsl_course.list_orgs                       # JSON to stdout
    python3 -m dsl_course.list_orgs --format markdown     # Markdown tables
    python3 -m dsl_course.list_orgs --format yaml         # YAML
    python3 -m dsl_course.list_orgs --update-file PATH    # write the full MD page
"""

from __future__ import annotations

import argparse
import json
import sys

import yaml

from .central import resolve_central_ref
from .course import COHORT_TOPIC, COURSE_HUB_TOPIC
from .discovery import discover_cohorts
from .gh_contents import load_yaml_config
from .ghcli import gh_json
from .log import log_err
from .repos import org_exists

# How many results one `gh search repos` page returns. This inventory is fully generated
# and merged unattended, so silently reading only the first page would quietly delete every
# org past it from the page - _tagged_orgs raises instead when the result set fills the
# limit. Raise this (gh allows up to 1000) when the estate outgrows it.
SEARCH_LIMIT = 100

# The full inventory page. Entirely generated - hand edits are overwritten on the next
# refresh, so layout/prose changes belong HERE, not in the .md.
PAGE = """\
# Bootstrapped Orgs - Live Inventory

> Auto-generated by the `refresh-inventory` workflow - do not hand-edit.

## Orgs

Each course org carries the toolkit tier its seeded workflows run the engine from
(`central_ref` in its `.github/dsl-course.yml`); its cohorts inherit it.

{tree}

## Regenerate on demand

To regenerate:

```bash
python3 -m dsl_course.list_orgs --update-file bootstrapped-orgs-inventory.md
```

Or run **Refresh Course Orgs Inventory** from the Actions tab.
"""


def _tagged_orgs(topic: str) -> list[str]:
    """Owner logins of every LIVE `.github` repo carrying `topic`.

    Raises when the search comes back exactly full: that is indistinguishable from a
    truncated result set, and an inventory silently missing its tail is worse than none.

    Every hit is then confirmed to still exist (`org_exists`) - the search index lags
    org deletion by days, so the topic alone is not evidence the org is there."""
    results = gh_json(
        "search",
        "repos",
        f"topic:{topic}",
        "--limit",
        str(SEARCH_LIMIT),
        "--json",
        "name,owner",
    )
    if len(results) >= SEARCH_LIMIT:
        raise RuntimeError(
            f"`gh search repos topic:{topic}` returned the full {SEARCH_LIMIT}-result "
            f"page, so the result set is truncated and any org past it would be dropped "
            f"from the inventory. Raise SEARCH_LIMIT in dsl_course/list_orgs.py."
        )

    owners = []
    for repo in results:
        if repo.get("name") != ".github":
            continue
        owner = (repo.get("owner") or {}).get("login", "")
        if owner and org_exists(owner):
            owners.append(owner)
    return owners


def discover_course_orgs() -> list[dict]:
    """Find every `.github` repo tagged `dsl-course-hub` and fetch its metadata.

    Returns a list of dicts with keys: org, org_name, course_name, course_code,
    central_ref, url. Sorted by org name.
    """
    orgs = []
    for owner in _tagged_orgs(COURSE_HUB_TOPIC):
        meta = _metadata_or_none(owner)
        if meta is None:
            # Carried through with a null tier rather than dropped: the page must still
            # show the org (an absence reads as "deleted"), and a null matches no tier,
            # so Promote's fan-out skips exactly this org and refreshes the rest.
            orgs.append(
                {
                    "org": owner,
                    "org_name": owner,
                    "course_name": "",
                    "course_code": "",
                    "central_ref": None,
                    "url": f"https://github.com/{owner}",
                }
            )
            continue
        if meta.get("course"):
            # A cohort org's dsl-course.yml is a pointer back to its course org
            # (`course:`/`org:` keys only). Cohorts bootstrapped before the topic split
            # still carry dsl-course-hub on their .github, so filter them here too -
            # this inventory enumerates COURSE orgs, never their per-year cohorts.
            continue
        orgs.append(
            {
                "org": owner,
                "org_name": meta.get("org_name", owner),
                "course_name": meta.get("course_name", ""),
                "course_code": meta.get("course_code", ""),
                # The deployment tier this course (and every cohort under it) runs. Read
                # off the metadata already fetched, so the page costs no extra call to say
                # which orgs a promotion would move.
                "central_ref": resolve_central_ref(
                    meta.get("central_ref"),
                    source=f"{owner}/.github/dsl-course.yml",
                ),
                "url": f"https://github.com/{owner}",
            }
        )

    orgs.sort(key=lambda o: o["org"].lower())
    return orgs


def discover_cohort_orgs() -> list[dict]:
    """Find every `.github` repo tagged `dsl-cohort` and read its course pointer.

    Returns a list of dicts with keys: org, course, url - sorted by course org, then
    cohort, so the table groups each course's deliveries together.
    """
    cohorts = []
    for owner in _tagged_orgs(COHORT_TOPIC):
        meta = _metadata_or_none(owner)
        cohorts.append(
            {
                "org": owner,
                # None is "could not read it", distinct from "" - a genuinely absent or
                # null `course:` key. Both end up under Orphaned, saying which.
                "course": None if meta is None else (meta.get("course") or ""),
                "url": f"https://github.com/{owner}",
            }
        )
    cohorts.sort(key=lambda c: ((c["course"] or "").lower(), c["org"].lower()))
    return cohorts


def _fetch_metadata(org: str) -> dict:
    """Read and parse `.github/dsl-course.yml` for an org.

    {} means the org genuinely carries no metadata (a 404, or an empty file); any other
    read failure raises. The tier split reads this file - `course:` present means a
    cohort - so a transient failure would file a cohort org under Course orgs, and the
    inventory is fully generated: a wrong refresh is worse than no refresh.

    Through `load_yaml_config`, so there is one reader for this file. Its own copy of the
    404 test drifted from `ghcli.is_missing_resource`, and its `except Exception: return
    {}` turned a MALFORMED dsl-course.yml into "this org declares nothing" - which files a
    cohort under Course orgs and rewrites the inventory around it, exactly the wrong
    refresh this docstring warns about."""
    return load_yaml_config(org, ".github", "dsl-course.yml") or {}


def _metadata_or_none(org: str) -> dict | None:
    """`org`'s metadata, or None when it could not be read.

    A malformed `dsl-course.yml` in ONE org used to abort every consumer of this module.
    For the inventory that is the right answer and is still what happens (see `main`),
    but Promote's fan-out reads the same listing to decide which orgs to refresh, and one
    org's typo leaving the whole estate un-refreshed is not a trade worth making. So the
    failure is logged and localised to that org here, and the caller decides."""
    try:
        return _fetch_metadata(org)
    except RuntimeError as exc:
        log_err(f"{org}: could not read .github/dsl-course.yml - {exc}")
        return None


def unreadable(orgs: list[dict], cohorts: list[dict]) -> list[str]:
    """The orgs whose metadata this run could not read - see _metadata_or_none."""
    return sorted(
        [o["org"] for o in orgs if o["central_ref"] is None]
        + [c["org"] for c in cohorts if c["course"] is None]
    )


def _registered_cohorts(course_org: str) -> list[str]:
    """What the course org's registry claims, for comparison against what GitHub shows.

    Read through discovery so there is ONE parser for that file - the registry raises on a
    malformed one, and this page would rather fail than render a course as running nothing
    because its registry could not be read."""
    return discover_cohorts(course_org)


def render_tree(orgs: list[dict], cohorts: list[dict]) -> str:
    """The estate as it is actually shaped: each course org, with the cohort orgs that
    point at it nested underneath.

    Two flat tables kept the two tiers apart and made the reader join them by eye - which
    is the one question this page is ever opened to answer ("what is running under this
    course?"). Nesting answers it directly, and a course org with no cohorts becomes
    visible as such rather than being an absence from a second table.

    A cohort whose `course:` pointer names an org that is NOT a discovered course org is
    ORPHANED - the pointer is dangling, or its course org lost its `dsl-course-hub` topic.
    Those cannot nest anywhere, so they are listed at the end rather than dropped: an
    orphan is a fault to fix, and silently omitting it is how it stays unfixed.

    A cohort that exists but is NOT REGISTERED in its course's cohort-courses-pages.yml is
    marked as such. It is a live org that every nightly sync is blind to - membership,
    faculty, site, scheduler all fan out from that registry - so it fails by doing nothing
    at all, which is the one failure mode nothing else here reports. Marked, never
    auto-registered: absence from the registry can be deliberate (a cohort paused on
    purpose), so the page says what it sees and leaves the decision to a person."""
    by_course: dict[str, list[dict]] = {}
    for c in cohorts:
        by_course.setdefault(c["course"], []).append(c)

    lines = []
    for o in orgs:
        name = " - ".join(x for x in (o["course_name"], o["course_code"]) if x)
        lines.append(
            f"- **[{o['org']}]({o['url']})**"
            + (f" - {name}" if name else "")
            + (
                " - **dsl-course.yml unreadable**"
                if o["central_ref"] is None
                else f" - toolkit `{o['central_ref']}`"
            )
        )
        registered = set(_registered_cohorts(o["org"]))
        mine = by_course.pop(o["org"], [])
        lines += [
            f"    - [{c['org']}]({c['url']})"
            + ("" if c["org"] in registered else " - **not registered**")
            for c in mine
        ] or ["    - _no cohorts yet_"]

    # Whatever is left over points at no course org this run discovered.
    orphans = [c for rest in by_course.values() for c in rest]
    if orphans:
        lines.append("")
        lines.append("**Orphaned cohort orgs** _(no course org discovered for them)_:")
        lines += [
            f"- [{c['org']}]({c['url']}) -> "
            + (
                "**dsl-course.yml unreadable**"
                if c["course"] is None
                else f"`{c['course'] or 'no course: pointer'}`"
            )
            for c in sorted(orphans, key=lambda c: c["org"].lower())
        ]
    return "\n".join(lines)


def render_page(orgs: list[dict], cohorts: list[dict]) -> str:
    """The complete inventory page - PAGE with the org tree filled in."""
    return PAGE.format(tree=render_tree(orgs, cohorts))


def update_file(path: str, page: str) -> bool:
    """Write the fully generated page to `path`. Returns True if the file changed."""
    from pathlib import Path

    p = Path(path)
    if p.exists() and p.read_text() == page:
        return False

    p.write_text(page)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--format",
        choices=["json", "markdown", "yaml"],
        default="json",
        help="Output format when writing to stdout. Default: json.",
    )
    parser.add_argument(
        "--update-file",
        default=None,
        help="Markdown file to (over)write with the fully generated inventory page.",
    )
    args = parser.parse_args()

    # Discovery is one `gh search repos` call per topic; if it fails there is no
    # inventory to write. Report it as a line in the Actions log, not a traceback.
    try:
        orgs = discover_course_orgs()
        cohorts = discover_cohort_orgs()
    except RuntimeError as exc:
        log_err(str(exc))
        return 1

    # The page is fully generated and merged unattended, so an org this run could not
    # read must not be written out as if the listing were complete. The JSON/YAML forms
    # still print - Promote reads them, and a null tier is a value it can act on - but the
    # exit code says the picture is partial either way.
    partial = unreadable(orgs, cohorts)
    if partial:
        log_err(
            "could not read the metadata of: "
            + ", ".join(partial)
            + " - the inventory below is incomplete"
        )

    if args.update_file:
        if partial:
            return 1
        changed = update_file(args.update_file, render_page(orgs, cohorts))
        print(
            f"{'updated' if changed else 'no change'}: {args.update_file} "
            f"({len(orgs)} course orgs, {len(cohorts)} cohort orgs)"
        )
        return 0

    combined = {"course_orgs": orgs, "cohort_orgs": cohorts}
    if args.format == "json":
        print(json.dumps(combined, indent=2))
    elif args.format == "yaml":
        print(yaml.safe_dump(combined, sort_keys=False))
    else:
        print(render_tree(orgs, cohorts))

    return 1 if partial else 0


if __name__ == "__main__":
    sys.exit(main())
