"""Pure content transforms behind the two websites - the logic with real edge cases.

The headline invariant: a PUBLIC course-site entry must never link into a private repo
(github.com / raw.githubusercontent), only site-relative paths. reading-list mode must
publish citations as text without leaking copyrighted bytes.
"""

from __future__ import annotations

from datetime import date, datetime
from unittest.mock import patch
from zoneinfo import ZoneInfo

import pytest
import yaml

from dsl_course import gh_contents, public_site, repos, schedule_plan, site, site_repo


def test_semester_label():
    assert site._semester_label("Deep-Learning-f2026") == "Fall 2026"
    assert site._semester_label("Intro-s2025") == "Spring 2025"
    assert site._semester_label("no-tag-here") == ""


def test_slug():
    assert site_repo.slug("MidTerm Exam") == "midterm-exam"
    assert site_repo.slug("") == "exam"


def test_exam_entry_date_only_keeps_the_nine_am_placeholder():
    # Unchanged rendering for every schedule that gives a bare `date:` (and for the
    # synthesised mid/end-of-semester fallback rows).
    out = site._exam_entry("MidTerm Exam", date(2026, 11, 3))
    assert "date: 2026-11-03T09:00:00" in out
    assert 'description: "MidTerm Exam"' in out
    assert "type: exam" in out


def test_exam_entry_renders_the_real_time_when_one_was_given():
    out = site._exam_entry(
        "Final Exam", datetime(2026, 12, 15, 14, 0, tzinfo=ZoneInfo("Europe/Berlin"))
    )
    assert "date: 2026-12-15T14:00:00" in out
    assert "09:00" not in out
    assert "+01:00" not in out  # offset-free, like the assignment due rows


_PEOPLE_META = {
    "people": {
        "instructors": [{"name": "Prof. Jane", "photo": "j.jpg", "url": "u/jane"}],
        "teaching_assistants": [{"name": "Alex TA", "photo": "a.jpg", "url": "u/alex"}],
    }
}


def test_people_yaml_cohort_includes_tas():
    # The cohort site reads its own people.yml and renders instructors AND TAs.
    out = site_repo.people_yaml("Some-Cohort-f2026", _PEOPLE_META, edit_at="people.yml")
    assert "Prof. Jane" in out
    assert "Alex TA" in out


def test_people_yaml_course_site_drops_tas():
    # The multi-year open-courseware site shows instructors only - TAs are cohort-only.
    out = site_repo.people_yaml(
        "Some-Course", _PEOPLE_META, edit_at="dsl-course.yml", include_tas=False
    )
    assert "Prof. Jane" in out
    assert "Alex TA" not in out
    assert "teaching_assistants:" in out  # the (now empty) key is still emitted


def test_people_yaml_header_says_it_is_generated_and_where_to_edit(monkeypatch):
    # An instructor edited the generated file and the next sync overwrote him. Both modes
    # - declared block and team fallback - must say so and name the real source file.
    declared = site_repo.people_yaml(
        "Some-Cohort-f2026", _PEOPLE_META, edit_at="Cohort/classroom-config/people.yml"
    )
    monkeypatch.setattr(site_repo, "_team_people", lambda org, team: [])
    fallback = site_repo.people_yaml(
        "Some-Course",
        {},
        edit_at="the `people:` block of Course/.github/dsl-course.yml",
    )
    for out in (declared, fallback):
        assert "GENERATED by the DSL course sync" in out
        assert "do not edit" in out
        assert "Every sync rewrites" in out
    assert "Cohort/classroom-config/people.yml" in declared
    assert "Course/.github/dsl-course.yml" in fallback


def test_people_yaml_passes_every_declared_display_field_through():
    # `title` used to be the only optional field and was special-cased; anything else a
    # course declared was silently dropped. Every display field must now reach the card,
    # so adding one is a theme change only.
    meta = {
        "people": {
            "instructors": [
                {
                    "github_handle": "jane",  # access-only - must NOT reach the card
                    "start": "2020-01-01",
                    "end": "2999-12-31",
                    "name": "Prof. Jane",
                    "photo": "j.jpg",
                    "url": "u/jane",
                    "title": "Professor of Things",
                    "office_hours": "Tue 14:00, Room 3.21",
                }
            ]
        }
    }
    out = site_repo.people_yaml("Some-Cohort-f2026", meta, edit_at="people.yml")
    assert 'title: "Professor of Things"' in out
    assert 'office_hours: "Tue 14:00, Room 3.21"' in out
    assert 'profile_pic: "j.jpg"' in out  # `photo` renamed to the theme's key
    assert 'webpage: "u/jane"' in out  # `url` renamed to the theme's key
    for access_only in ("github_handle", "start:", "end:"):
        assert access_only not in out


def test_replacing_a_config_scalar_touches_only_the_named_key():
    cfg = 'course_name: "old"\ncourse_code: "X"\n'
    out = site_repo._replace_config_scalar(cfg, "course_name", "Deep Learning")
    assert 'course_name: "Deep Learning"' in out
    assert 'course_code: "X"' in out  # untouched


def test_reading_list_md_inlines_text_lists_binaries_by_name(tmp_path):
    wk = tmp_path / "session-1"
    wk.mkdir()
    (wk / "READINGS.md").write_text("# Session 1\n- Smith 2020, ch.1")
    (wk / "paper.pdf").write_bytes(b"%PDF-1.4 copyrighted bytes")
    md = public_site._reading_list_md(wk)
    assert "Smith 2020" in md  # citation text is published
    assert "- paper.pdf" in md  # the PDF is named...
    assert "%PDF" not in md  # ...but its bytes are NOT


def test_public_links_are_site_relative(tmp_path):
    wk = tmp_path / "lectures"
    wk.mkdir()
    (wk / "01 intro.pdf").write_bytes(b"x")
    links = public_site._public_links(
        wk, "/public-materials/course-materials-f2026/session-1/lectures"
    )
    assert len(links) == 1
    name, url = links[0]
    assert name == "01 intro.pdf"
    assert url.startswith("/public-materials/")
    assert "%20" in url or "01%20intro" in url  # space URL-encoded
    assert "github.com" not in url and "raw." not in url


def test_public_lecture_entry_reading_list_mode_has_no_links():
    e = public_site._public_lecture_entry("1", date(2025, 1, 1), [], "- Smith 2020")
    assert "links: []" in e
    # The citation text rides the front matter, not the body: both sites then feed the
    # theme's Materials layout from one field, and it needs no `{% raw %}` fence.
    assert "reading_list: |" in e and "Smith 2020" in e
    assert "enrolled" not in e  # public-facing, no student gate language


def test_lecture_entry_labels_links_by_repo_or_subpath():
    def fake_session_files(org, repo, subpath, folder):
        return {
            ("labs", ""): [("intro.pdf", "https://x/1")],  # root shape: label = repo
            ("materials", "lectures"): [
                ("slides.pdf", "https://x/2")
            ],  # nested: label = subpath
        }.get((repo, subpath), [])

    with (
        patch.object(site, "_session_files", side_effect=fake_session_files),
        patch.object(site, "_repo_tree", return_value=("main", ())),
    ):
        entry = site._lecture_entry(
            "Cohort-f2026",
            "1",
            schedule_plan.PlannedRow(when=date(2026, 9, 7)),
            [("labs", "", "01_intro"), ("materials", "lectures", "01_intro")],
        )
    assert "https://x/1" in entry and "https://x/2" in entry
    assert 'name: "lab - intro.pdf"' in entry
    assert 'name: "lecture - slides.pdf"' in entry


def test_public_lecture_entry_actual_readings_mode_links_are_local():
    lec = [("s.pdf", "/public-materials/m/session-1/lectures/s.pdf")]
    rds = [("r.pdf", "/public-materials/m/session-1/readings/r.pdf")]
    e = public_site._public_lecture_entry(
        "1", date(2025, 1, 1), [("lectures", lec), ("readings", rds)], ""
    )
    assert "lecture - s.pdf" in e and "reading - r.pdf" in e
    assert "github.com" not in e and "raw." not in e


def test_public_lecture_entry_renders_a_lab_row_as_its_own_type():
    # Same split as the cohort site: the labs section is its own row, so the theme's labs
    # page finds it and the session row doesn't list it twice.
    e = public_site._public_lecture_entry(
        "2",
        date(2025, 1, 1),
        [("labs", [("lab.ipynb", "/public-materials/m/session-2/labs/lab.ipynb")])],
        "",
        "lab",
    )
    assert "type: lab" in e
    assert 'title: "Lab 2"' in e
    assert 'name: "lab - lab.ipynb"' in e


def test_row_file_splits_labs_from_lectures():
    assert site_repo.row_file("2", "lab") == "lab-02.md"
    assert site_repo.row_file("2", "lecture") == "session-02.md"


def test_public_lecture_entry_labels_any_discovered_section():
    # Sections are free-form directory names - a repo with labs/ and faq/ must get
    # labelled links, not silently nothing (the site used to look only at lectures/).
    e = public_site._public_lecture_entry(
        "3",
        date(2025, 1, 1),
        [
            ("labs", [("lab3.ipynb", "/public-materials/m/session-3/labs/lab3.ipynb")]),
            ("faq", [("faq.md", "/public-materials/m/session-3/faq/faq.md")]),
        ],
        "",
    )
    assert 'name: "lab - lab3.ipynb"' in e
    assert 'name: "faq - faq.md"' in e  # not "fa - faq.md"


def test_singular_strips_only_a_real_trailing_s():
    assert site_repo._singular("lectures") == "lecture"
    assert site_repo._singular("labs") == "lab"
    assert site_repo._singular("faq") == "faq"  # was "fa"
    assert site_repo._singular("s") == "s"  # never empty


_TREE = "\n".join(  # noqa: FLY002 - a list of paths reads better than one long f-string
    [
        "README.md",
        "lectures/03_week-3/notes.pdf",
        "lectures/03_week-3/handouts/extra notes.pdf",
        "lectures/03_week-3/handouts/deep/further.md",
        "lectures/03_week-30/decoy.pdf",  # prefix-sharing sibling, must not leak in
        "lectures/04_week-4/other.pdf",
        "01_intro/root-shape.pdf",
    ]
)


def _tree_gh(*args, **kwargs):
    """Fake `gh api .../git/trees/<branch>?recursive=1` - the `truncated` flag the jq asks
    for first, then the repo's blob paths."""
    return (0, "false\n" + _TREE)


def test_session_files_lists_nested_files_by_path(monkeypatch):
    # release.py copytrees a session folder wholesale, so nested files ARE released -
    # a non-recursive listing dropped them from the site entirely.
    monkeypatch.setattr(site, "default_branch", lambda org, repo, **k: "main")
    monkeypatch.setattr(gh_contents, "gh", _tree_gh)
    pairs = site._session_files("Cohort-f2026", "materials", "lectures", "03_week-3")
    assert [n for n, _ in pairs] == [
        "handouts/deep/further.md",  # sorted by path, so nested first
        "handouts/extra notes.pdf",
        "notes.pdf",
    ]
    urls = dict(pairs)
    assert (
        urls["notes.pdf"]
        == "https://github.com/Cohort-f2026/materials/blob/main/lectures/03_week-3/notes.pdf"
    )
    assert "extra%20notes.pdf" in urls["handouts/extra notes.pdf"]  # spaces encoded


def test_session_files_root_shape_and_other_sessions_excluded(monkeypatch):
    monkeypatch.setattr(site, "default_branch", lambda org, repo, **k: "main")
    monkeypatch.setattr(gh_contents, "gh", _tree_gh)
    # subpath="" - the release landed at the repo root (default destination)
    assert site._session_files("Cohort-f2026", "lectures", "", "01_intro") == [
        (
            "root-shape.pdf",
            "https://github.com/Cohort-f2026/lectures/blob/main/01_intro/root-shape.pdf",
        )
    ]


def test_repo_tree_is_fetched_once_per_repo(monkeypatch):
    # A cohort site asks for the files of every released session, nearly always from the
    # same repo - one tree fetch must serve them all, not one fetch per session.
    calls = []

    def counting_gh(*args, **kwargs):
        calls.append(args)
        return (0, _TREE)

    monkeypatch.setattr(site, "default_branch", lambda org, repo, **k: "main")
    monkeypatch.setattr(gh_contents, "gh", counting_gh)
    for folder in ("03_week-3", "04_week-4", "03_week-30"):
        assert site._session_files("Cohort-f2026", "materials", "lectures", folder)
    assert len(calls) == 1


def test_session_files_absent_repo_is_empty(monkeypatch):
    # A genuine 404 (repo/tree absent) is empty - gh's real wording, case included.
    monkeypatch.setattr(site, "default_branch", lambda org, repo, **k: "main")
    monkeypatch.setattr(
        gh_contents, "gh", lambda *a, **k: (1, "gh: Not Found (HTTP 404)")
    )
    assert site._session_files("Cohort-f2026", "materials", "lectures", "03_x") == []


def test_session_files_real_failure_raises(monkeypatch):
    # A non-404 failure must NOT be read as "no files" (which republishes the site with
    # every material link stripped) - it raises instead.
    monkeypatch.setattr(site, "default_branch", lambda org, repo, **k: "main")
    monkeypatch.setattr(
        gh_contents, "gh", lambda *a, **k: (1, "gh: HTTP 500 Server Error")
    )
    with pytest.raises(RuntimeError, match="could not read the tree"):
        site._session_files("Cohort-f2026", "materials", "lectures", "03_x")


# --------------------------------------------------------------- display link shaping
# A released session folder is copied WHOLESALE, so a rendered Quarto/Rmd deck arrives as
# one deliverable plus hundreds of assets. These pin the split between what SHIPS (all of
# it, recursively - `_session_files`) and what a row LISTS (`_shape_links`). The shape
# below is the real `lectures/01_introduction` of hertie-intro-to-data-science-f2025,
# whose site carried 200 links for this one session.
ITDS_SESSION_01 = [
    ("01-introduction.Rmd", "https://x/rmd"),
    ("01-introduction.html", "https://x/html"),
    ("01-introduction.pdf", "https://x/pdf"),
    ("01-introduction_files/figure-html/indeed-1.svg", "https://x/fig"),
    ("add_hertie_logo.html", "https://x/logo"),
    ("libs/fabric/fabric.min.js", "https://x/fabric"),
    ("libs/remark-css/metropolis.css", "https://x/metro"),
    ("pics/1_1_hello.png", "https://x/p1"),
    ("pics/1_2_data.png", "https://x/p2"),
    ("simons-touch.css", "https://x/css"),
]
TREE = "https://github.com/o/r/tree/main/lectures/01_introduction"


def test_shape_links_lists_root_files_and_folds_subfolders():
    names = [n for n, _ in site._shape_links(ITDS_SESSION_01, TREE, frozenset())]
    # 10 blobs -> 5 root files + one entry per subfolder, in path order, files first.
    assert names == [
        "01-introduction.Rmd",
        "01-introduction.html",
        "01-introduction.pdf",
        "add_hertie_logo.html",
        "simons-touch.css",
        "01-introduction_files/ (1 file)",
        "libs/ (2 files)",
        "pics/ (2 files)",
    ]


def test_shape_links_points_a_folded_folder_at_its_tree():
    got = dict(site._shape_links(ITDS_SESSION_01, TREE, frozenset()))
    assert got["pics/ (2 files)"] == f"{TREE}/pics"
    # A file still links to the file, not to its folder.
    assert got["01-introduction.pdf"] == "https://x/pdf"


def test_shape_links_allowlist_matches_at_any_depth_and_offers_the_folder():
    names = [
        n
        for n, _ in site._shape_links(ITDS_SESSION_01, TREE, frozenset({"pdf", "css"}))
    ]
    # Nothing is hidden without a way back: the browse link is the escape hatch.
    assert names == [
        "01-introduction.pdf",
        "libs/remark-css/metropolis.css",
        "simons-touch.css",
        site._BROWSE_ALL,
    ]
    assert (
        dict(site._shape_links(ITDS_SESSION_01, TREE, frozenset({"pdf"})))[
            site._BROWSE_ALL
        ]
        == TREE
    )


def test_shape_links_leaves_a_flat_folder_untouched():
    # The worked example's shape: no subfolders, so there is nothing to fold and the row
    # reads exactly as it did before any of this.
    flat = [("slides.md", "https://x/1"), ("demo.py", "https://x/2")]
    assert site._shape_links(flat, TREE, frozenset()) == flat


def test_shape_links_lists_dotfiles_like_any_other_file():
    # No name filter, deliberately. The exclusion list this would need cannot be written
    # honestly: `__pycache__/` and `node_modules/` are clutter and are not dotted, while
    # `.Rprofile` is course material an R course's students need. So the page says what was
    # released, and clutter is fixed by not releasing it.
    # Path-sorted, as `_session_files` hands them over ('.R' sorts before '.g').
    blobs = [
        (".Rprofile", "https://x/rprofile"),
        (".gitkeep", "https://x/keep"),
        ("media/.gitkeep", "https://x/mk"),
        ("media/fig.png", "https://x/fig"),
        ("slides.pdf", "https://x/pdf"),
    ]
    names = [n for n, _ in site._shape_links(blobs, TREE, frozenset())]
    # `.gitkeep` rides along: the cost of not hiding `.Rprofile`, and it disappears by
    # itself the moment real content lands in that folder.
    assert names == [".Rprofile", ".gitkeep", "slides.pdf", "media/ (2 files)"]


def test_the_index_lists_dotfiles_too(monkeypatch):
    # Same rule on the other page, which is the point of not having two.
    repos = {"m": ("01_lab/.Rprofile", "01_lab/lab.R", "01_lab/.gitkeep")}
    entry = _index(monkeypatch, repos)[0]["entries"][0]
    assert entry["name"] == "01_lab/" and entry["files"] == 3


def test_ext_reads_the_extension_not_a_dotted_directory():
    assert site._ext("notes.PDF") == "pdf"
    assert site._ext("Makefile") == ""
    assert site._ext("libs/remark-css/metropolis.css") == "css"
    # A dot in a directory name is not the file's extension.
    assert site._ext("v1.2/README") == ""


def test_the_allowlist_never_leaves_a_public_file_unreachable(tmp_path):
    # Jekyll serves no directory index, so the public site has no folder link and no
    # browse-the-folder escape hatch. An allowlist there would copy a file, serve it, and
    # link it from nowhere - so `site_link_extensions` governs the cohort site only.
    (tmp_path / "libs").mkdir()
    (tmp_path / "deck.html").write_text("x")
    (tmp_path / "notes.pdf").write_text("x")
    (tmp_path / "libs" / "style.css").write_text("x")
    names = [n for n, _ in public_site._public_links(tmp_path, "/m/session-1")]
    assert names == [
        "deck.html",
        "notes.pdf",
    ]  # root files listed, the asset served only


def test_public_links_lists_nested_files_when_nothing_sits_at_the_root(tmp_path):
    # The fold means "these are the assets of that deliverable". With no root file they are
    # not assets, they are the material - and this host has no folder link to offer
    # instead, so folding them would serve them and link them from nowhere. Worse, a
    # section with no links is skipped, so the session would get no page at all.
    (tmp_path / "handouts").mkdir()
    (tmp_path / "handouts" / "notes.pdf").write_text("x")
    (tmp_path / "handouts" / "extra.pdf").write_text("x")
    names = [n for n, _ in public_site._public_links(tmp_path, "/m/session-1")]
    assert names == ["handouts/extra.pdf", "handouts/notes.pdf"]


def test_link_extensions_accepts_a_list_or_a_bare_string():
    assert site._link_extensions(
        {"site_link_extensions": [".PDF", "html"]}
    ) == frozenset({"pdf", "html"})
    # The shape faculty reach for first; refusing it would only mean a silently
    # unfiltered site.
    assert site._link_extensions({"site_link_extensions": "pdf, html"}) == frozenset(
        {"pdf", "html"}
    )
    assert site._link_extensions({}) == frozenset()
    assert site._link_extensions({"site_link_extensions": []}) == frozenset()


# --------------------------------------------------------------- reading lists + blocks
def test_block_survives_an_indented_first_line():
    # Without the explicit `|2` indicator YAML would take the block's indentation from its
    # first line, and every following line would look like the end of the block - breaking
    # the whole file, not just this field.
    out = site_repo.block("reading_list", "   - indented\n- flush")
    assert yaml.safe_load(out)["reading_list"] == "   - indented\n- flush\n"


def test_block_keeps_liquid_verbatim_and_expands_tabs():
    # Front matter is data, not a template, so no `{% raw %}` fence is needed here.
    text = "a\tb\n{{ site.x }} {% if y %}"
    assert (
        yaml.safe_load(site_repo.block("k", text))["k"]
        == "a   b\n{{ site.x }} {% if y %}\n"
    )


def _readings_sources():
    return [("materials", "readings", "01_week-1"), ("materials", "lectures", "01_x")]


def test_released_reading_list_inlines_text_and_ignores_the_pdf(monkeypatch):
    files = {
        ("materials", "readings", "01_week-1"): [
            ("READINGS.md", "u"),
            ("blitzstein_ch1.pdf", "u"),
        ],
        ("materials", "lectures", "01_x"): [("slides.pdf", "u")],
    }
    monkeypatch.setattr(
        site, "_session_files", lambda o, r, s, f: files.get((r, s, f), [])
    )
    monkeypatch.setattr(
        site,
        "get_file_content",
        lambda org, repo, path: (
            "- Blitzstein, ch. 1-2." if path.endswith("READINGS.md") else ""
        ),
    )
    out = site._released_reading_list("Cohort-f2026", _readings_sources())
    # The citation text is the list; the PDF is left to the links beside it (this site
    # repo is public, so it never hosts the reading itself).
    assert out == "- Blitzstein, ch. 1-2."


def test_released_reading_list_propagates_a_read_failure(monkeypatch):
    # A rate-limited read must not republish the row with the reading list silently
    # emptied - same rule as every other fail-loud read in this module.
    monkeypatch.setattr(
        site, "_session_files", lambda o, r, s, f: [("READINGS.md", "u")]
    )

    def boom(*a, **k):
        raise RuntimeError("could not read")

    monkeypatch.setattr(site, "get_file_content", boom)
    with pytest.raises(RuntimeError):
        site._released_reading_list("Cohort-f2026", [("materials", "readings", "01_a")])


def test_row_links_drops_the_citation_file_it_already_inlined(monkeypatch):
    monkeypatch.setattr(site, "_repo_tree", lambda org, repo: ("main", ()))
    monkeypatch.setattr(
        site,
        "_session_files",
        lambda o, r, s, f: [
            ("READINGS.md", "https://x/md"),
            ("ch1.pdf", "https://x/pdf"),
        ],
    )
    names = [
        n for n, _ in site._row_links("C", "materials", "readings", "01_a", frozenset())
    ]
    assert names == ["ch1.pdf"]  # READINGS.md IS the list, not a download beside it
    # Any other section keeps its text files - only `readings` inlines the overlay.
    names = [
        n for n, _ in site._row_links("C", "materials", "lectures", "01_a", frozenset())
    ]
    assert "READINGS.md" in names


def test_row_links_keeps_an_uploaded_text_file_that_is_not_the_overlay(monkeypatch):
    # The bug the name-based rule fixes: subtracting by EXTENSION took an uploaded
    # `notes.md` or `refs.bib` - a reading in its own right - out of the downloads too, so a
    # student could not get it. Only the overlay is ever subtracted.
    monkeypatch.setattr(site, "_repo_tree", lambda org, repo: ("main", ()))
    monkeypatch.setattr(
        site,
        "_session_files",
        lambda o, r, s, f: [
            ("READINGS.md", "https://x/overlay"),
            ("notes.md", "https://x/notes"),
            ("refs.bib", "https://x/refs"),
            ("ch1.pdf", "https://x/pdf"),
        ],
    )
    names = [
        n for n, _ in site._row_links("C", "materials", "readings", "01_a", frozenset())
    ]
    assert "READINGS.md" not in names  # its content is already inlined on the row
    assert sorted(names) == ["ch1.pdf", "notes.md", "refs.bib"]


# ------------------------------------------------------- the All Materials catch-all index
# The two shapes real cohorts actually have. Both must land where a reader expects, and the
# ordinal must decide only the LEVEL a section is read at - never whether a file is listed.
DEMO_REPOS = {  # repo per section, ordinals at the repo root
    "lectures": ("01_introduction/slides.md", "01_introduction/demo.py", "README.md"),
    "readings": ("01_introduction/reading-list.md",),
}
MATHS_REPOS = {  # one materials repo, sections inside it
    "materials": (
        "lectures/01_lecture/deck.html",
        "lectures/01_lecture/media/img.png",
        "labs/01_lab/lab.ipynb",
        "datasets/housing.csv",
        "SYLLABUS.md",
        ".DS_Store",
        ".github/workflows/x.yml",
    )
}


def _parse(monkeypatch, repos):
    monkeypatch.setattr(
        site, "_repo_tree", lambda o, r: ("main", tuple(sorted(repos[r])))
    )
    return yaml.safe_load(site._materials_index("Cohort-f2026", list(repos)))


def _index(monkeypatch, repos):
    return _parse(monkeypatch, repos)["sections"]


def _docs(monkeypatch, repos):
    return [d["name"] for d in _parse(monkeypatch, repos).get("documents", [])]


def test_root_documents_are_one_group_not_a_section_per_repo(monkeypatch):
    # The syllabus and the README are course-level documents, not sections. Keying them by
    # the repo they sit in listed each of them once per content repo - three READMEs on the
    # live demo site, one under each of lectures, labs and readings.
    repos = {
        "labs": ("01_lab/lab.ipynb", "README.md", "SYLLABUS.md"),
        "lectures": ("01_intro/deck.html", "README.md", "SYLLABUS.md"),
    }
    monkeypatch.setattr(site, "_repo_tree", lambda o, r: ("main", repos[r]))
    got = yaml.safe_load(site._materials_index("C", sorted(repos)))
    assert [d["name"] for d in got["documents"]] == ["README.md", "SYLLABUS.md"]
    # ...and they are gone from the sections, which now hold only session folders.
    assert [s["name"] for s in got["sections"]] == ["labs", "lectures"]
    for section in got["sections"]:
        assert [e["name"] for e in section["entries"]] == [
            f"01_{'lab' if section['name'] == 'labs' else 'intro'}/"
        ]


def test_a_cohort_with_only_root_documents_is_not_reported_as_empty(monkeypatch):
    monkeypatch.setattr(site, "_repo_tree", lambda o, r: ("main", ("SYLLABUS.md",)))
    got = yaml.safe_load(site._materials_index("C", ["materials"]))
    assert [d["name"] for d in got["documents"]] == ["SYLLABUS.md"]
    assert got["sections"] == []


def test_index_reads_a_repo_per_section_cohort(monkeypatch):
    got = {
        s["name"]: [e["name"] for e in s["entries"]]
        for s in _index(monkeypatch, DEMO_REPOS)
    }
    # The repo names the section and its ordinal folders are the entries. The root
    # README.md is a course document, listed once rather than under a repo's heading.
    assert got == {"lectures": ["01_introduction/"], "readings": ["01_introduction/"]}
    assert _docs(monkeypatch, DEMO_REPOS) == ["README.md"]


def test_index_reads_a_single_materials_repo_cohort(monkeypatch):
    sections = _index(monkeypatch, MATHS_REPOS)
    got = {s["name"]: [e["name"] for e in s["entries"]] for s in sections}
    # Each top-level directory is its own section here, and `datasets/` needs no ordinal
    # anywhere to appear. The root SYLLABUS.md takes the repo's name.
    #
    # `.DS_Store` and `.github/` show up too, which is the deliberate cost of filtering
    # nothing by name: a rule about dots would also hide `.Rprofile`. Neither can normally
    # reach a cohort repo - `deploy.ROOT_RELEASE_EXCLUDED` never releases a root `.github`,
    # and OS cruft only arrives if someone commits it - so if either is here, it was
    # released on purpose and saying so is right.
    assert got == {
        ".github": ["workflows/"],
        "datasets": ["housing.csv"],
        "labs": ["01_lab/"],
        "lectures": ["01_lecture/"],
    }
    # The root files are course documents now, not a section named after the repo.
    assert _docs(monkeypatch, MATHS_REPOS) == [".DS_Store", "SYLLABUS.md"]


def test_index_folds_a_directory_to_one_counted_link(monkeypatch):
    lectures = next(
        s for s in _index(monkeypatch, MATHS_REPOS) if s["name"] == "lectures"
    )
    entry = lectures["entries"][0]
    # Never the directory's contents: one of these holds a couple of thousand files.
    assert entry["name"] == "01_lecture/" and entry["files"] == 2
    assert entry["url"].endswith("/tree/main/lectures/01_lecture")
    assert lectures["files"] == 2


def test_index_links_a_file_as_a_blob_and_counts_no_files(monkeypatch):
    datasets = next(
        s for s in _index(monkeypatch, MATHS_REPOS) if s["name"] == "datasets"
    )
    entry = datasets["entries"][0]
    assert entry["url"].endswith("/blob/main/datasets/housing.csv")
    assert "files" not in entry  # a file is not a folder with a count


def test_index_nests_a_directory_instead_of_only_folding_it(monkeypatch):
    # The All Materials tab shows the whole shape of what shipped, not just a count -
    # unlike a session row's links (`_shape_links`), a folded subfolder's contents ARE
    # reachable in the page itself, at any depth.
    lectures = next(
        s for s in _index(monkeypatch, MATHS_REPOS) if s["name"] == "lectures"
    )
    top = lectures["entries"][0]
    assert top["name"] == "01_lecture/"
    nested = {e["name"]: e for e in top["entries"]}
    assert set(nested) == {"deck.html", "media/"}
    assert "entries" not in nested["deck.html"] and "files" not in nested["deck.html"]
    assert nested["deck.html"]["url"].endswith(
        "/blob/main/lectures/01_lecture/deck.html"
    )
    media = nested["media/"]
    assert media["files"] == 1
    assert [e["name"] for e in media["entries"]] == ["img.png"]
    assert media["entries"][0]["url"].endswith(
        "/blob/main/lectures/01_lecture/media/img.png"
    )


def test_index_is_empty_yaml_when_nothing_is_released(monkeypatch):
    monkeypatch.setattr(site, "_repo_tree", lambda o, r: ("main", ()))
    assert yaml.safe_load(site._materials_index("Cohort-f2026", ["materials"])) == {
        "sections": []
    }
    # And with no repos at all, without touching the tree.
    assert yaml.safe_load(site._materials_index("Cohort-f2026", [])) == {"sections": []}


def test_index_puts_directories_before_files(monkeypatch):
    # Both in ONE section, which needs the ordinal shape: a non-ordinal directory would
    # become a section of its own rather than an entry beside the root file.
    repos = {"m": ("01_zzz/a.txt", "01_zzz/aaa.md")}
    entries = [e["name"] for e in _index(monkeypatch, repos)[0]["entries"]]
    # A directory listing: the structure is what a reader scans first, unlike a session
    # row, which leads with its deliverables.
    assert entries == ["01_zzz/"]


def test_index_gives_a_non_ordinal_directory_its_own_section(monkeypatch):
    # The rule that makes both cohort shapes work: an ordinal child means the REPO is the
    # section, a non-ordinal one means the DIRECTORY is.
    repos = {"m": ("handbook/rules.md", "aaa.md")}
    sections = _index(monkeypatch, repos)
    assert {s["name"]: [e["name"] for e in s["entries"]] for s in sections} == {
        "handbook": ["rules.md"]
    }
    # ...and the root file is a course document, not a section named after the repo.
    assert _docs(monkeypatch, repos) == ["aaa.md"]


def test_theme_pages_split_readings_out_only_where_there_is_an_index():
    cohort = site_repo.theme_pages(cohort=True)
    assert "layout: readings" in cohort["readings.md"]
    assert "layout: materials" in cohort["materials.md"]
    assert "All Materials" in cohort["materials.md"]
    # A public course site has no cohort repos to index, so /materials/ stays the readings
    # page it has always been rather than becoming an empty catch-all.
    public = site_repo.theme_pages(cohort=False)
    assert "readings.md" not in public
    assert "layout: readings" in public["materials.md"]
    assert "permalink: /materials/" in public["materials.md"]


def test_every_page_states_its_own_access_rule():
    cohort = site_repo.theme_pages(cohort=True)
    # Each page's gate is its own sentence, because they genuinely differ: readings are a
    # public citation list over gated files, the rest are gated outright.
    # auditors read released materials but get no assignments, so the three materials
    # pages name them and the assignments page does not
    assert "enrolled students & auditors." in cohort["lectures.md"]
    assert "enrolled students & auditors." in cohort["labs.md"]
    assert "enrolled students & auditors." in cohort["readings.md"]
    assert "only accessible to enrolled students/auditors." in cohort["materials.md"]
    assert "only accessible to enrolled students." in cohort["assignments.md"]
    assert "auditors" not in cohort["assignments.md"]
    # The public open-courseware site publishes the same files on purpose, so it claims no
    # gate anywhere.
    for page in site_repo.theme_pages(cohort=False).values():
        assert "enrolled" not in page


def test_no_nav_tab_can_point_at_a_page_this_site_does_not_get():
    # The tab bar and the pages come from one table, and BOTH syncs generate the nav - so
    # the public site cannot ship a Readings tab pointing at a page only cohort sites get.
    for cohort in (True, False):
        tabs = {
            i["url"] for i in yaml.safe_load(site_repo.nav_yaml(cohort=cohort))["items"]
        }
        generated = {
            f"/{f.removesuffix('.md')}/" for f in site_repo.theme_pages(cohort=cohort)
        }
        assert generated <= tabs  # every generated page has a tab
        # ...and every remaining tab is one the theme provides rather than generates.
        assert tabs - generated == {"/", "/schedule/"}
    public = {
        i["url"] for i in yaml.safe_load(site_repo.nav_yaml(cohort=False))["items"]
    }
    assert "/readings/" not in public  # a cohort-only page, so a cohort-only tab


def test_nav_order_does_not_depend_on_a_string_tie_break():
    # Assignments used to be pinned to integer position 5, which tied with the fourth
    # generated page - so the tab order came down to comparing "/assignments/" against
    # "/materials/". It now follows the page it belongs behind.
    names = [
        i["name"] for i in yaml.safe_load(site_repo.nav_yaml(cohort=True))["items"]
    ]
    # Assignments is a generated page now, so its position comes from the page table like
    # every other - no integer slots, nothing to tie.
    assert names.index("Assignments") == names.index("Readings") + 1
    assert names.index("All Materials") == names.index("Assignments") + 1


def test_describe_keeps_the_paragraphs_of_a_multi_line_objective():
    # Hertie learning objectives run to a paragraph, sometimes two. `_q` folds newlines, so
    # a one-line scalar silently ran them together.
    one = site._describe("Sample spaces and Bayes' rule.")
    assert one == 'description: "Sample spaces and Bayes\' rule."\n'
    many = site._describe("First paragraph.\n\nSecond paragraph.")
    assert (
        yaml.safe_load(many)["description"] == "First paragraph.\n\nSecond paragraph.\n"
    )
    assert site._describe("") == "" and site._describe("   ") == ""


def test_a_planned_destination_links_only_where_something_exists(monkeypatch):
    # The path itself cannot exist - that is what "not released" means - so linking it
    # would hand a student a 404. The deepest ancestor that IS there gets the link.
    monkeypatch.setattr(
        site, "_repo_tree", lambda o, r: ("main", ("lectures/01_intro/slides.pdf",))
    )
    live = frozenset({"materials"})
    # The repo exists and holds `lectures/`, but not `lectures/03_week-3` yet.
    got = site._dest_link("C", "materials/lectures/03_week-3", live)
    assert (
        got
        == "[`materials/lectures/03_week-3`](https://github.com/C/materials/tree/main/lectures)"
    )
    # A repo that does not exist yet has nothing to link at all.
    assert site._dest_link("C", "labs/01_lab", live) == "`labs/01_lab`"
    # A repo that exists but is empty links the repo itself.
    monkeypatch.setattr(site, "_repo_tree", lambda o, r: ("main", ()))
    assert site._dest_link("C", "materials/lectures/03", live) == (
        "[`materials/lectures/03`](https://github.com/C/materials)"
    )


# ----------------------------------------------------- finding a released syllabus
def test_the_syllabus_is_found_under_any_name_and_format(monkeypatch):
    # Faculty name it; we only have to find it. ITDS really does use the PDF.
    for name in ("SYLLABUS.md", "SYLLABUS.pdf", "syllabus-2026.docx", "Syllabus.MD"):
        monkeypatch.setattr(site, "_repo_tree", lambda o, r, n=name: ("main", (n,)))
        assert site._released_syllabus("C", ["materials"]) == (
            f"https://github.com/C/materials/blob/main/{name}"
        )


def test_a_syllabus_image_inside_a_session_folder_is_not_the_syllabus(monkeypatch):
    # A live cohort has `lectures/01_introduction/pics/ids-syllabus-2024.png`. Root files
    # only, or the home page links a screenshot.
    monkeypatch.setattr(
        site,
        "_repo_tree",
        lambda o, r: (
            "main",
            ("lectures/01_x/pics/ids-syllabus-2024.png", "lectures/01_x/deck.html"),
        ),
    )
    assert site._released_syllabus("C", ["materials"]) is None


def test_no_syllabus_means_no_key_at_all(monkeypatch):
    # The home page shows no line rather than an empty one, so the key must be absent -
    # not present and blank.
    monkeypatch.setattr(
        site, "_repo_tree", lambda o, r: ("main", ("lectures/01/a.md",))
    )
    assert "syllabus" not in yaml.safe_load(site._materials_index("C", ["materials"]))
    with_one = yaml.safe_load(site._materials_index("C", ["materials"], syllabus="u"))
    assert with_one["syllabus"] == "u"


def test_an_exact_syllabus_stem_beats_a_longer_name(monkeypatch):
    # Plain sorting put `SYLLABUS-draft.pdf` ahead of `SYLLABUS.pdf` ('-' sorts before
    # '.'), so a cohort shipping a draft alongside the real thing pinned the draft on its
    # front page.
    monkeypatch.setattr(
        site,
        "_repo_tree",
        lambda o, r: ("main", ("SYLLABUS-draft.pdf", "SYLLABUS.pdf")),
    )
    assert site._released_syllabus("C", ["m"]).endswith("/SYLLABUS.pdf")


def test_a_longer_name_is_still_used_when_it_is_all_there_is(monkeypatch):
    monkeypatch.setattr(
        site, "_repo_tree", lambda o, r: ("main", ("syllabus-2026.docx",))
    )
    assert site._released_syllabus("C", ["m"]).endswith("/syllabus-2026.docx")


def test_the_syllabus_choice_is_stable_when_a_cohort_has_two(monkeypatch):
    # A link that moves between syncs is worse than either choice. Determinism comes from
    # the caller's sorted repo list and _repo_tree's sorted paths, not from re-sorting.
    trees = {"zzz": ("SYLLABUS.md",), "aaa": ("SYLLABUS.md",)}
    monkeypatch.setattr(site, "_repo_tree", lambda o, r: ("main", trees[r]))
    assert site._released_syllabus("C", ["aaa", "zzz"]).endswith(
        "/aaa/blob/main/SYLLABUS.md"
    )


def _repos(*names):
    return [{"name": n} for n in names]


def test_a_renamed_org_fails_the_sync_instead_of_no_opping(monkeypatch):
    # Renaming an org leaves `<old>.github.io` behind, demoted to a project page. The
    # expected site repo is then absent, which used to read as "never opted into a site"
    # - green forever while the published site rotted.
    monkeypatch.setattr(site_repo, "repo_exists", lambda org, name: False)
    monkeypatch.setattr(
        site_repo, "list_org_repos", lambda org: _repos("welcome", "OLD-NAME.github.io")
    )
    built: list[object] = []
    assert site_repo.sync_site_repo("new-name", lambda wd: built.append(wd)) == 1
    assert built == []


def test_an_org_that_never_had_a_site_is_still_a_quiet_noop(monkeypatch):
    monkeypatch.setattr(site_repo, "repo_exists", lambda org, name: False)
    monkeypatch.setattr(
        site_repo, "list_org_repos", lambda org: _repos("welcome", ".github")
    )
    assert site_repo.sync_site_repo("new-name", lambda wd: None) == 0


def test_a_failed_repo_listing_is_not_read_as_no_site(monkeypatch):
    monkeypatch.setattr(site_repo, "repo_exists", lambda org, name: False)

    def boom(org):
        raise RuntimeError(f"could not list repos in {org}")

    monkeypatch.setattr(site_repo, "list_org_repos", boom)
    assert site_repo.sync_site_repo("new-name", lambda wd: None) == 1


# ------------------------------------------------------- the publication denylist


def test_the_all_materials_index_hides_what_should_never_have_shipped(monkeypatch):
    # The catch-all index lists everything a release happened to carry, so it was the
    # shortest route from "someone released a folder wholesale" to "the whole class has
    # the answers".
    repos = {
        "labs": (
            "01_lab/lab.ipynb",
            "01_lab/solution/answers.ipynb",
            "01_lab/grading.yml",
            "01_lab/Tests/test_hidden.py",
            ".env.production",
            "README.md",
        )
    }
    got = _parse(monkeypatch, repos)
    assert [d["name"] for d in got["documents"]] == ["README.md"]
    entries = got["sections"][0]["entries"]
    assert [e["name"] for e in entries] == ["01_lab/"]
    assert [e["name"] for e in entries[0]["entries"]] == ["lab.ipynb"]


def test_a_denylisted_file_is_never_linked_from_a_public_page(tmp_path):
    (tmp_path / "deck.html").write_text("slides")
    (tmp_path / "grading.yml").write_text("points: 10")
    (tmp_path / ".env").write_text("KEY=live")
    links = public_site._public_links(tmp_path, "/m/session-1/lectures")
    assert [name for name, _ in links] == ["deck.html"]


def test_the_denylist_matches_by_name_at_any_depth_and_ignores_case():
    assert repos.has_denied_component("labs/01_lab/Solution/answers.ipynb")
    assert repos.has_denied_component("tests/test_x.py")
    assert repos.has_denied_component("a/.env.local")
    # ...and does not swallow a file that merely contains a denylisted word.
    assert not repos.has_denied_component("labs/01_lab/solutions-discussion.md")
    assert not repos.has_denied_component("labs/testing-guide.md")
