"""Pure content transforms behind the two websites - the logic with real edge cases.

The headline invariant: a PUBLIC course-site entry must never link into a private repo
(github.com / raw.githubusercontent), only site-relative paths. reading-list mode must
publish citations as text without leaking copyrighted bytes.
"""

from __future__ import annotations

from datetime import date, datetime
from textwrap import indent
from zoneinfo import ZoneInfo

import pytest
import yaml

from dsl_course import (
    gh_contents,
    materials,
    policy,
    public_site,
    repos,
    site,
    site_repo,
)
from dsl_course.schedule import Deploy, Release, Schedule
from dsl_course.site_repo import Link
from tests.conftest import entry_links, repo_row


def test_semester_label():
    assert site._semester_label("Deep-Learning-f2026") == "Fall 2026"
    assert site._semester_label("Intro-s2025") == "Spring 2025"
    assert site._semester_label("no-tag-here") == ""


def test_slug():
    assert site_repo.slug("MidTerm Exam") == "midterm-exam"
    assert site_repo.slug("") == "exam"


def test_exam_entry_date_only_keeps_the_nine_am_placeholder():
    # Unchanged rendering for every schedule that gives a bare `date:` (and for the
    # synthesised mid/end-of-semester fallback rows).
    out = site._event_row("exam", "MidTerm Exam", date(2026, 11, 3))
    assert "date: 2026-11-03T09:00:00" in out
    assert 'title: "MidTerm Exam"' in out
    assert "type: exam" in out


def test_exam_entry_renders_the_real_time_when_one_was_given():
    out = site._event_row(
        "exam",
        "Final Exam",
        datetime(2026, 12, 15, 14, 0, tzinfo=ZoneInfo("Europe/Berlin")),
    )
    assert "date: 2026-12-15T14:00:00" in out
    assert "09:00" not in out
    assert "+01:00" not in out  # offset-free, like the assignment due rows


_PEOPLE_META = {
    "people": {
        "instructors": [{"name": "Prof. Jane", "photo": "j.jpg", "url": "u/jane"}],
        "teaching_assistants": [{"name": "Alex TA", "photo": "a.jpg", "url": "u/alex"}],
    }
}


def test_people_yaml_semester_includes_tas():
    # The semester site reads its own instructors.yml and renders instructors AND TAs.
    out = site_repo.people_yaml(
        "Some-Semester-f2026", _PEOPLE_META, edit_at="instructors.yml"
    )
    assert "Prof. Jane" in out
    assert "Alex TA" in out


def test_people_yaml_course_site_drops_tas():
    # The multi-year open-courseware site shows instructors only - TAs are semester-only.
    out = site_repo.people_yaml(
        "Some-Course", _PEOPLE_META, edit_at="dsl-course.yml", include_tas=False
    )
    assert "Prof. Jane" in out
    assert "Alex TA" not in out
    assert "teaching_assistants:" in out  # the (now empty) key is still emitted


def test_people_yaml_header_says_it_is_generated_and_where_to_edit(monkeypatch):
    # An instructor edited the generated file and the next sync overwrote him. Both modes
    # - declared block and team fallback - must say so and name the real source file.
    declared = site_repo.people_yaml(
        "Some-Semester-f2026",
        _PEOPLE_META,
        edit_at="Semester/semester-config/instructors.yml",
    )
    monkeypatch.setattr(site_repo, "_team_people", lambda org, team: [])
    fallback = site_repo.people_yaml(
        "Some-Course",
        {},
        edit_at="the `people:` block of Course/.github/dsl-course.yml",
    )
    for out in (declared, fallback):
        assert "GENERATED by the DSL course sync" in out
        assert "do not edit" in out
        assert "Every sync rewrites" in out
    assert "Semester/semester-config/instructors.yml" in declared
    assert "Course/.github/dsl-course.yml" in fallback


def test_people_yaml_passes_every_declared_display_field_through():
    # `title` used to be the only optional field and was special-cased; anything else a
    # course declared was silently dropped. Every display field must now reach the card,
    # so adding one is a theme change only.
    meta = {
        "people": {
            "instructors": [
                {
                    "github_handle": "jane",  # access-only - must NOT reach the card
                    "start": "2020-01-01",
                    "end": "2999-12-31",
                    "name": "Prof. Jane",
                    "photo": "j.jpg",
                    "url": "u/jane",
                    "title": "Professor of Things",
                    "office_hours": "Tue 14:00, Room 3.21",
                }
            ]
        }
    }
    out = site_repo.people_yaml("Some-Semester-f2026", meta, edit_at="instructors.yml")
    assert 'title: "Professor of Things"' in out
    assert 'office_hours: "Tue 14:00, Room 3.21"' in out
    assert 'profile_pic: "j.jpg"' in out  # `photo` renamed to the theme's key
    assert 'webpage: "u/jane"' in out  # `url` renamed to the theme's key
    for access_only in ("github_handle", "start:", "end:"):
        assert access_only not in out


def test_people_yaml_keeps_the_declared_email_off_the_card_by_default():
    # `email:` is REQUIRED in instructors.yml (it is what a fault notification is sent to), so
    # publishing it by default would put an address given for notifications on a public
    # website - for every instructor and TA of every semester, without anyone opting in.
    meta = {
        "people": {
            "instructors": [
                {"name": "Prof. Jane", "title": "Professor", "email": "jane@x.org"}
            ],
            "teaching_assistants": [{"name": "Alex TA", "email": "alex@x.org"}],
        }
    }
    out = site_repo.people_yaml("Some-Semester-f2026", meta, edit_at="instructors.yml")
    assert "jane@x.org" not in out
    assert "alex@x.org" not in out
    assert 'title: "Professor"' in out  # the rest of the card is untouched


def test_people_yaml_publishes_the_email_only_on_an_exact_show_email_true():
    # The opt-in, and it must fail closed: a `show_email` a maintainer mistyped (`"yes"`)
    # would otherwise publish an address nobody agreed to publish. `show_email` itself is
    # a switch this side consumes and must never reach the site either.
    meta = {
        "people": {
            "instructors": [
                {"name": "Prof. Jane", "email": "jane@x.org", "show_email": True},
                {"name": "Dr Sam", "email": "sam@x.org", "show_email": "yes"},
            ],
            "teaching_assistants": [
                {"name": "Alex TA", "email": "alex@x.org", "show_email": False}
            ],
        }
    }
    out = site_repo.people_yaml("Some-Semester-f2026", meta, edit_at="instructors.yml")
    assert 'email: "jane@x.org"' in out  # opted in
    assert "sam@x.org" not in out  # not the string "yes"
    assert "alex@x.org" not in out  # opted out explicitly
    # CARD_ORDER puts a published address after `name`, so the file has a stable shape
    assert out.index('name: "Prof. Jane"') < out.index('email: "jane@x.org"')
    assert "show_email" not in out  # none of the three values


def test_replacing_a_config_scalar_touches_only_the_named_key():
    cfg = 'course_name: "old"\ncourse_code: "X"\n'
    out = site_repo._replace_config_scalar(cfg, "course_name", "Deep Learning")
    assert 'course_name: "Deep Learning"' in out
    assert 'course_code: "X"' in out  # untouched


def test_reading_list_md_inlines_text_lists_binaries_by_name(tmp_path):
    wk = tmp_path / "session-1"
    wk.mkdir()
    (wk / "READINGS.md").write_text("# Session 1\n- Smith 2020, ch.1")
    (wk / "paper.pdf").write_bytes(b"%PDF-1.4 copyrighted bytes")
    md = public_site._reading_list_md(wk, lambda p: True)
    assert "Smith 2020" in md  # citation text is published
    assert "- paper.pdf" in md  # the PDF is named...
    assert "%PDF" not in md  # ...but its bytes are NOT


def test_reading_list_md_drops_a_withheld_reading_before_naming_it(tmp_path):
    # `reading-list` is the DEFAULT mode and hosts nothing, so it never calls copy_tree and
    # the copytree ignore hook never runs. Naming a file IS publishing it here, and an
    # inlined overlay publishes every word - so a withheld reading has to be dropped before
    # `readings_block` sees it, not filtered out of a copy that never happened.
    wk = tmp_path / "session-1"
    wk.mkdir()
    (wk / "READINGS.md").write_text("# Session 1\n- Smith 2020, ch.1")
    (wk / "embargoed.pdf").write_bytes(b"%PDF not yet")
    md = public_site._reading_list_md(wk, lambda p: p.name != "embargoed.pdf")
    assert "Smith 2020" in md
    assert "embargoed" not in md


def test_reading_list_md_can_withhold_the_overlay_itself(tmp_path):
    # The worse half of the same hole: the overlay is INLINED, so a withheld one published
    # its full prose rather than merely its name.
    wk = tmp_path / "session-1"
    wk.mkdir()
    (wk / "READINGS.md").write_text("# Session 1\n- unpublished draft citation")
    (wk / "paper.pdf").write_bytes(b"%PDF")
    md = public_site._reading_list_md(wk, lambda p: p.name != "READINGS.md")
    assert "unpublished draft citation" not in md
    assert "- paper.pdf" in md


def test_public_links_are_site_relative(tmp_path):
    wk = tmp_path / "lectures"
    wk.mkdir()
    (wk / "01 intro.pdf").write_bytes(b"x")
    links = public_site._public_links(
        wk, "/public-materials/course-materials-f2026/session-1/lectures"
    )
    assert len(links) == 1
    link = links[0]
    assert link.name == "01 intro.pdf"
    assert link.url.startswith("/public-materials/")
    assert "%20" in link.url or "01%20intro" in link.url  # space URL-encoded
    assert "github.com" not in link.url and "raw." not in link.url
    # The public course site HOSTS everything it links, so a link there never carries a
    # second destination.
    assert link.view_url == ""


def test_public_lecture_entry_reading_list_mode_has_no_links():
    e = public_site._public_lecture_entry("1", date(2025, 1, 1), [], "- Smith 2020")
    assert "links: []" in e
    # The citation text rides the front matter, not the body: both sites then feed the
    # theme's Materials layout from one field, and it needs no `{% raw %}` fence.
    assert "reading_list: |" in e and "Smith 2020" in e
    assert "enrolled" not in e  # public-facing, no student gate language


def test_public_lecture_entry_actual_readings_mode_links_are_local():
    lec = [Link("s.pdf", "/public-materials/m/session-1/lectures/s.pdf")]
    rds = [Link("r.pdf", "/public-materials/m/session-1/readings/r.pdf")]
    e = public_site._public_lecture_entry(
        "1", date(2025, 1, 1), [("lectures", lec), ("readings", rds)], ""
    )
    links = entry_links(e)
    assert ("lecture", "s.pdf") in links and ("reading", "r.pdf") in links
    assert "github.com" not in e and "raw." not in e


def test_public_lecture_entry_renders_a_lab_row_as_its_own_type():
    # Same split as the semester site: the labs section is its own row, so the theme's labs
    # page finds it and the session row doesn't list it twice.
    e = public_site._public_lecture_entry(
        "2",
        date(2025, 1, 1),
        [("labs", [Link("lab.ipynb", "/public-materials/m/session-2/labs/lab.ipynb")])],
        "",
        "lab",
    )
    assert "type: lab" in e
    assert 'title: "Lab 2"' in e
    assert ("lab", "lab.ipynb") in entry_links(e)


def test_row_file_splits_labs_from_lectures():
    assert site_repo.row_file("2", "lab") == "lab-02.md"
    assert site_repo.row_file("2", "lecture") == "session-02.md"


def test_public_lecture_entry_labels_any_discovered_section():
    # Sections are free-form directory names - a repo with labs/ and faq/ must get
    # labelled links, not silently nothing (the site used to look only at lectures/).
    e = public_site._public_lecture_entry(
        "3",
        date(2025, 1, 1),
        [
            (
                "labs",
                [Link("lab3.ipynb", "/public-materials/m/session-3/labs/lab3.ipynb")],
            ),
            ("faq", [Link("faq.md", "/public-materials/m/session-3/faq/faq.md")]),
        ],
        "",
    )
    links = entry_links(e)
    assert ("lab", "lab3.ipynb") in links
    assert ("faq", "faq.md") in links  # not section "fa"


def test_singular_strips_only_a_real_trailing_s():
    assert site_repo._singular("lectures") == "lecture"
    assert site_repo._singular("labs") == "lab"
    assert site_repo._singular("faq") == "faq"  # was "fa"
    assert site_repo._singular("s") == "s"  # never empty


_TREE = "\n".join(  # noqa: FLY002 - a list of paths reads better than one long f-string
    [
        "README.md",
        "lectures/03_week-3/notes.pdf",
        "lectures/03_week-3/handouts/extra notes.pdf",
        "lectures/03_week-3/handouts/deep/further.md",
        "lectures/03_week-30/decoy.pdf",  # prefix-sharing sibling, must not leak in
        "lectures/04_week-4/other.pdf",
        "01_intro/root-shape.pdf",
    ]
)


def _tree_gh(*args, **kwargs):
    """Fake `gh api .../git/trees/<branch>?recursive=1` - the `truncated` flag the jq asks
    for first, then the repo's blob paths."""
    return (0, "false\n" + _TREE)


def _deploy(path, repo="materials", dest=None):
    return Deploy("cm", path, repo, dest)


def _landed(monkeypatch, deploy, readings=False, gh=_tree_gh):
    monkeypatch.setattr(site, "default_branch", lambda org, repo, **k: "main")
    monkeypatch.setattr(gh_contents, "gh", gh)
    return site._landed("Semester-f2026", deploy, frozenset(), {}, readings)


def test_a_landed_folder_links_its_files_and_folds_its_subfolders(monkeypatch):
    # A release copies a folder wholesale, so nested files ARE released: they are one
    # folded link away, and the prefix-sharing `03_week-30` is not this folder.
    landed = _landed(monkeypatch, _deploy("lectures/03_week-3"))
    assert [x.name for x in landed.links] == ["notes.pdf", "handouts/ (2 files)"]
    assert landed.section == "lectures" and not landed.root_file
    assert landed.links[0].url == (
        "https://github.com/Semester-f2026/materials/blob/main/lectures/03_week-3/notes.pdf"
    )


def test_a_landed_file_is_one_link_wherever_it_sits(monkeypatch):
    # The demo's lecture code: a single file outside any session folder, now linked.
    landed = _landed(
        monkeypatch, _deploy("dldemo/a.pdf", dest="lectures/04_week-4/other.pdf")
    )
    assert [x.name for x in landed.links] == ["other.pdf"]
    assert not landed.root_file
    assert _landed(monkeypatch, _deploy("README.md")).root_file


def test_a_whole_repo_copy_lands_the_repo(monkeypatch):
    landed = _landed(monkeypatch, _deploy(""))
    assert landed.section == "materials"
    assert "README.md" in [x.name for x in landed.links]


def test_nothing_landed_yet_is_none_and_a_failed_read_raises(monkeypatch):
    assert _landed(monkeypatch, _deploy("lectures/05_week-5")) is None
    # A genuine 404 (repo/tree absent) has landed nothing.
    site._repo_tree.cache_clear()
    assert (
        _landed(
            monkeypatch,
            _deploy("lectures/03_week-3", repo="gone"),
            gh=lambda *a, **k: (1, "gh: Not Found (HTTP 404)"),
        )
        is None
    )
    # Any other failure must not read as "not released" - it raises.
    site._repo_tree.cache_clear()
    with pytest.raises(RuntimeError, match="could not read the tree"):
        _landed(
            monkeypatch,
            _deploy("x", repo="flaky"),
            gh=lambda *a, **k: (1, "gh: HTTP 500 Server Error"),
        )


def test_the_tree_is_fetched_once_per_repo(monkeypatch):
    calls = []

    def counting_gh(*args, **kwargs):
        calls.append(args)
        return (0, _TREE)

    site._repo_tree.cache_clear()
    for folder in ("lectures/03_week-3", "lectures/04_week-4", "01_intro"):
        assert _landed(monkeypatch, _deploy(folder, repo="once"), gh=counting_gh)
    assert len(calls) == 1


_READINGS_TREE = (
    "readings/01_week-1/READINGS.md",
    "readings/01_week-1/notes.md",
    "readings/01_week-1/refs.bib",
    "readings/01_week-1/ch1.pdf",
)


def test_a_readings_row_inlines_its_overlay_and_lists_everything_else(monkeypatch):
    monkeypatch.setattr(site, "_repo_tree", lambda org, repo: ("main", _READINGS_TREE))
    landed = site._landed("C", _deploy("readings/01_week-1"), frozenset(), {}, True)
    # Only the overlay is taken out: an uploaded `notes.md` or `refs.bib` is a reading.
    assert sorted(x.name for x in landed.links) == ["ch1.pdf", "notes.md", "refs.bib"]
    assert landed.overlays == ["readings/01_week-1/READINGS.md"]
    monkeypatch.setattr(
        site, "get_file_content", lambda org, repo, path: "# Week 1\n\n- Blitzstein."
    )
    assert site._reading_list("C", [landed]) == "### Week 1\n\n- Blitzstein."
    # Any other kind keeps the overlay as a file.
    other = site._landed("C", _deploy("readings/01_week-1"), frozenset(), {}, False)
    assert "READINGS.md" in [x.name for x in other.links] and not other.overlays


def test_a_reading_list_read_failure_propagates(monkeypatch):
    def boom(*a, **k):
        raise RuntimeError("could not read")

    monkeypatch.setattr(site, "get_file_content", boom)
    landed = site._Landed("materials", "readings", [], ["readings/01/READINGS.md"])
    with pytest.raises(RuntimeError):
        site._reading_list("C", [landed])


def _syllabus(monkeypatch, releases, tree, declared=None):
    monkeypatch.setattr(site, "_repo_tree", lambda o, r: ("main", tree))
    monkeypatch.setattr(
        site, "read_materials", lambda o, r: declared or materials.Declared()
    )
    return site._declared_syllabus(
        "C", "S", Schedule(releases=releases), frozenset({"materials"}), {}
    )


def _intro(*deploys):
    return Release(
        "course-intro", datetime(2026, 9, 1, tzinfo=ZoneInfo("UTC")), list(deploys)
    )


def test_the_default_syllabus_is_pinned_where_its_copy_landed(monkeypatch):
    link = _syllabus(monkeypatch, [_intro(_deploy("SYLLABUS.md"))], ("SYLLABUS.md",))
    assert link == Link(
        "SYLLABUS.md", "https://github.com/S/materials/blob/main/SYLLABUS.md"
    )


def test_a_declared_syllabus_is_pinned_under_any_name(monkeypatch):
    # NLP's case: the syllabus is a PDF named for the course code.
    declared = materials.Declared(syllabus="E1282_syllabus.pdf")
    for deploy, tree in (
        (_deploy("E1282_syllabus.pdf"), ("E1282_syllabus.pdf",)),
        (_deploy(""), ("E1282_syllabus.pdf", "lectures/01/a.pdf")),  # the whole repo
        (_deploy("", dest="docs"), ("docs/E1282_syllabus.pdf",)),
    ):
        link = _syllabus(monkeypatch, [_intro(deploy)], tree, declared)
        assert link.name == "E1282_syllabus.pdf", deploy


def test_undeclared_and_absent_falls_back_to_a_root_syllab_file(monkeypatch):
    # Nothing declared and no SYLLABUS.md: the old root-file rule still pins, the exact
    # `syllabus.*` stem first - never a screenshot inside a folder.
    tree = (
        "lectures/01/pics/ids-syllabus-2024.png",
        "SYLLABUS-draft.pdf",
        "Syllabus.pdf",
    )
    link = _syllabus(monkeypatch, [_intro(_deploy("Syllabus.pdf"))], tree)
    assert link.name == "Syllabus.pdf"
    link = _syllabus(monkeypatch, [], tree[:2])
    assert link.name == "SYLLABUS-draft.pdf"
    assert _syllabus(monkeypatch, [], tree[:1]) is None


def test_a_declared_syllabus_is_never_second_guessed(monkeypatch):
    declared = materials.Declared(syllabus="E1282.pdf", declared=True)
    releases = [_intro(_deploy("readings/01"))]
    assert _syllabus(monkeypatch, releases, ("syllabus-old.pdf",), declared) is None


def test_an_off_plan_copy_of_the_syllabus_is_pinned(monkeypatch):
    # Released by hand: no entry names it, but it sits where the default says.
    link = _syllabus(monkeypatch, [], ("SYLLABUS.md", "syllabus-old.pdf"))
    assert link.name == "SYLLABUS.md"


def test_a_deck_carries_its_asset_folders_with_it():
    assert site._bundle_prefixes("lectures/01_lecture/deck.html") == (
        "lectures/01_lecture/deck_files/",
        "lectures/01_lecture/media/",
        "lectures/01_lecture/libs/",
        "lectures/01_lecture/images/",
    )


def test_a_hosted_deck_takes_a_media_folder_but_not_a_neighbours(tmp_path):
    # Maths keeps its deck assets in `media/` beside the deck.
    paths = (
        "lectures/01_lecture/deck.html",
        "lectures/01_lecture/media/fig.png",
        "lectures/01_lecture/notes.pdf",
        "lectures/02_lecture/media/other.png",
    )
    for rel in paths:
        (tmp_path / rel).parent.mkdir(parents=True, exist_ok=True)
        (tmp_path / rel).write_text("x")
    spec = site.parse_patterns("**/*.html")
    kept = site._public_selection(tmp_path, "materials", paths, (spec,))
    assert kept == {
        "lectures/01_lecture/deck.html",
        "lectures/01_lecture/media/fig.png",
    }


# --------------------------------------------------------------- display link shaping
# A released session folder is copied WHOLESALE, so a rendered Quarto/Rmd deck arrives as
# one deliverable plus hundreds of assets. These pin the split between what SHIPS (all of
# it, recursively - `_session_files`) and what a row LISTS (`_shape_links`). The shape
# below is the real `lectures/01_introduction` of hertie-intro-to-data-science-f2025,
# whose site carried 200 links for this one session.
ITDS_SESSION_01 = [
    Link("01-introduction.Rmd", "https://x/rmd"),
    Link("01-introduction.html", "https://x/html"),
    Link("01-introduction.pdf", "https://x/pdf"),
    Link("01-introduction_files/figure-html/indeed-1.svg", "https://x/fig"),
    Link("add_hertie_logo.html", "https://x/logo"),
    Link("libs/fabric/fabric.min.js", "https://x/fabric"),
    Link("libs/remark-css/metropolis.css", "https://x/metro"),
    Link("pics/1_1_hello.png", "https://x/p1"),
    Link("pics/1_2_data.png", "https://x/p2"),
    Link("simons-touch.css", "https://x/css"),
]
TREE = "https://github.com/o/r/tree/main/lectures/01_introduction"


def test_shape_links_lists_root_files_and_folds_subfolders():
    names = [x.name for x in site._shape_links(ITDS_SESSION_01, TREE, frozenset())]
    # 10 blobs -> 5 root files + one entry per subfolder, in path order, files first.
    assert names == [
        "01-introduction.Rmd",
        "01-introduction.html",
        "01-introduction.pdf",
        "add_hertie_logo.html",
        "simons-touch.css",
        "01-introduction_files/ (1 file)",
        "libs/ (2 files)",
        "pics/ (2 files)",
    ]


def test_shape_links_points_a_folded_folder_at_its_tree():
    got = {x.name: x.url for x in site._shape_links(ITDS_SESSION_01, TREE, frozenset())}
    assert got["pics/ (2 files)"] == f"{TREE}/pics"
    # A file still links to the file, not to its folder.
    assert got["01-introduction.pdf"] == "https://x/pdf"


def test_shape_links_allowlist_matches_at_any_depth_and_offers_the_folder():
    names = [
        x.name
        for x in site._shape_links(ITDS_SESSION_01, TREE, frozenset({"pdf", "css"}))
    ]
    # Nothing is hidden without a way back: the browse link is the escape hatch.
    assert names == [
        "01-introduction.pdf",
        "libs/remark-css/metropolis.css",
        "simons-touch.css",
        site._BROWSE_ALL,
    ]
    browse = site._shape_links(ITDS_SESSION_01, TREE, frozenset({"pdf"}))[-1]
    assert browse.name == site._BROWSE_ALL and browse.url == TREE


def test_shape_links_leaves_a_flat_folder_untouched():
    # The worked example's shape: no subfolders, so there is nothing to fold and the row
    # reads exactly as it did before any of this.
    flat = [Link("slides.md", "https://x/1"), Link("demo.py", "https://x/2")]
    assert site._shape_links(flat, TREE, frozenset()) == flat


def test_shape_links_lists_a_dotfile_but_not_a_never_material_name():
    # The rule is a closed list of NAMES, not a rule about dots: `.Rprofile` is course
    # material an R course's students need, while `.gitkeep` is only what holds an empty
    # folder open in git. A live semester site listed a session's `.gitkeep` as one of its
    # materials.
    # Path-sorted, as `_session_files` hands them over ('.R' sorts before '.g').
    blobs = [
        Link(".Rprofile", "https://x/rprofile"),
        Link(".gitkeep", "https://x/keep"),
        Link("media/.gitkeep", "https://x/mk"),
        Link("media/fig.png", "https://x/fig"),
        Link("slides.pdf", "https://x/pdf"),
    ]
    names = [x.name for x in site._shape_links(blobs, TREE, frozenset())]
    # ...and the fold counts what it shows: `media/` holds two blobs, one of them junk.
    assert names == [".Rprofile", "slides.pdf", "media/ (1 file)"]


def test_shape_links_drops_junk_from_the_allowlist_shape_too():
    # The allowlist matches by extension at any depth, so a `.ipynb_checkpoints/` copy of a
    # notebook is exactly the kind of thing it would otherwise list twice over.
    blobs = [
        Link(".ipynb_checkpoints/lab-checkpoint.ipynb", "https://x/ck"),
        Link("lab.ipynb", "https://x/lab"),
    ]
    names = [x.name for x in site._shape_links(blobs, TREE, frozenset({"ipynb"}))]
    assert names == ["lab.ipynb", site._BROWSE_ALL]


def test_shape_links_matches_a_directory_component_and_ignores_case():
    # Two of the names are DIRECTORIES, and a listing entry is a `/`-joined string, so the
    # match has to be component-wise. Case varies in the wild by whichever machine wrote
    # the file.
    blobs = [
        Link("__pycache__/helpers.cpython-312.pyc", "https://x/pyc"),
        Link(".DS_Store", "https://x/ds"),
        Link("data/.ds_store", "https://x/ds2"),
        Link("data/Thumbs.db", "https://x/th"),
        Link("data/housing.csv", "https://x/csv"),
    ]
    names = [x.name for x in site._shape_links(blobs, TREE, frozenset())]
    assert names == ["data/ (1 file)"]


def test_the_index_applies_the_same_name_rule(monkeypatch):
    # Same rule on the other page, which is the point of not having two.
    repos = {"m": ("01_lab/.Rprofile", "01_lab/lab.R", "01_lab/.gitkeep")}
    entry = _index(monkeypatch, repos)[0]["entries"][0]
    assert entry["name"] == "01_lab/" and entry["files"] == 2
    assert [e["name"] for e in entry["entries"]] == [".Rprofile", "lab.R"]


def test_the_index_folds_away_a_junk_directory_entirely(monkeypatch):
    # Not just the file: `__pycache__/` would otherwise be a directory entry of its own,
    # nested and counted, on the page that shows the whole shape of what shipped.
    repos = {"m": ("01_lab/__pycache__/helpers.cpython-312.pyc", "01_lab/lab.py")}
    entry = _index(monkeypatch, repos)[0]["entries"][0]
    assert entry["name"] == "01_lab/" and entry["files"] == 1
    assert [e["name"] for e in entry["entries"]] == ["lab.py"]


def test_ext_reads_the_extension_not_a_dotted_directory():
    assert site._ext("notes.PDF") == "pdf"
    assert site._ext("Makefile") == ""
    assert site._ext("libs/remark-css/metropolis.css") == "css"
    # A dot in a directory name is not the file's extension.
    assert site._ext("v1.2/README") == ""


def test_the_allowlist_never_leaves_a_public_file_unreachable(tmp_path):
    # Jekyll serves no directory index, so the public site has no folder link and no
    # browse-the-folder escape hatch. An allowlist there would copy a file, serve it, and
    # link it from nowhere - so `site_link_extensions` governs the semester site only.
    (tmp_path / "libs").mkdir()
    (tmp_path / "deck.html").write_text("x")
    (tmp_path / "notes.pdf").write_text("x")
    (tmp_path / "libs" / "style.css").write_text("x")
    names = [x.name for x in public_site._public_links(tmp_path, "/m/session-1")]
    assert names == [
        "deck.html",
        "notes.pdf",
    ]  # root files listed, the asset served only


def test_public_links_lists_nested_files_when_nothing_sits_at_the_root(tmp_path):
    # The fold means "these are the assets of that deliverable". With no root file they are
    # not assets, they are the material - and this host has no folder link to offer
    # instead, so folding them would serve them and link them from nowhere. Worse, a
    # section with no links is skipped, so the session would get no page at all.
    (tmp_path / "handouts").mkdir()
    (tmp_path / "handouts" / "notes.pdf").write_text("x")
    (tmp_path / "handouts" / "extra.pdf").write_text("x")
    names = [x.name for x in public_site._public_links(tmp_path, "/m/session-1")]
    assert names == ["handouts/extra.pdf", "handouts/notes.pdf"]


def test_link_extensions_accepts_a_list_or_a_bare_string():
    assert site._link_extensions(
        {"site_link_extensions": [".PDF", "html"]}
    ) == frozenset({"pdf", "html"})
    # The shape faculty reach for first; refusing it would only mean a silently
    # unfiltered site.
    assert site._link_extensions({"site_link_extensions": "pdf, html"}) == frozenset(
        {"pdf", "html"}
    )
    assert site._link_extensions({}) == frozenset()
    assert site._link_extensions({"site_link_extensions": []}) == frozenset()


# --------------------------------------------------------------- reading lists + blocks
def test_block_survives_an_indented_first_line():
    # Without the explicit `|2` indicator YAML would take the block's indentation from its
    # first line, and every following line would look like the end of the block - breaking
    # the whole file, not just this field.
    out = site_repo.block("reading_list", "   - indented\n- flush")
    assert yaml.safe_load(out)["reading_list"] == "   - indented\n- flush\n"


def test_block_keeps_liquid_verbatim_and_expands_tabs():
    # Front matter is data, not a template, so no `{% raw %}` fence is needed here.
    text = "a\tb\n{{ site.x }} {% if y %}"
    assert (
        yaml.safe_load(site_repo.block("k", text))["k"]
        == "a   b\n{{ site.x }} {% if y %}\n"
    )


# ------------------------------------------------------- the All Materials catch-all index
# The two shapes real semesters actually have. Both must land where a reader expects, and the
# ordinal must decide only the LEVEL a section is read at - never whether a file is listed.
DEMO_REPOS = {  # repo per section, ordinals at the repo root
    "lectures": ("01_introduction/slides.md", "01_introduction/demo.py", "README.md"),
    "readings": ("01_introduction/reading-list.md",),
}
MATHS_REPOS = {  # one materials repo, sections inside it
    "materials": (
        "lectures/01_lecture/deck.html",
        "lectures/01_lecture/media/img.png",
        "labs/01_lab/lab.ipynb",
        "datasets/housing.csv",
        "SYLLABUS.md",
        ".DS_Store",
        ".github/workflows/x.yml",
    )
}


def _parse(monkeypatch, repos):
    monkeypatch.setattr(
        site, "_repo_tree", lambda o, r: ("main", tuple(sorted(repos[r])))
    )
    return yaml.safe_load(site._materials_index("Semester-f2026", list(repos), {}))


def _index(monkeypatch, repos):
    return _parse(monkeypatch, repos)["sections"]


def _docs(monkeypatch, repos):
    return [d["name"] for d in _parse(monkeypatch, repos).get("documents", [])]


def test_root_documents_are_one_group_not_a_section_per_repo(monkeypatch):
    # The syllabus and the README are course-level documents, not sections. Keying them by
    # the repo they sit in listed each of them once per content repo - three READMEs on the
    # live demo site, one under each of lectures, labs and readings.
    repos = {
        "labs": ("01_lab/lab.ipynb", "README.md", "SYLLABUS.md"),
        "lectures": ("01_intro/deck.html", "README.md", "SYLLABUS.md"),
    }
    monkeypatch.setattr(site, "_repo_tree", lambda o, r: ("main", repos[r]))
    got = yaml.safe_load(site._materials_index("C", sorted(repos), {}))
    assert [d["name"] for d in got["documents"]] == ["README.md", "SYLLABUS.md"]
    # ...and they are gone from the sections, which now hold only session folders.
    assert [s["name"] for s in got["sections"]] == ["labs", "lectures"]
    for section in got["sections"]:
        assert [e["name"] for e in section["entries"]] == [
            f"01_{'lab' if section['name'] == 'labs' else 'intro'}/"
        ]


def test_a_semester_with_only_root_documents_is_not_reported_as_empty(monkeypatch):
    monkeypatch.setattr(site, "_repo_tree", lambda o, r: ("main", ("SYLLABUS.md",)))
    got = yaml.safe_load(site._materials_index("C", ["materials"], {}))
    assert [d["name"] for d in got["documents"]] == ["SYLLABUS.md"]
    assert got["sections"] == []


def test_index_reads_a_repo_per_section_semester(monkeypatch):
    got = {
        s["name"]: [e["name"] for e in s["entries"]]
        for s in _index(monkeypatch, DEMO_REPOS)
    }
    # The repo names the section and its ordinal folders are the entries. The root
    # README.md is a course document, listed once rather than under a repo's heading.
    assert got == {"lectures": ["01_introduction/"], "readings": ["01_introduction/"]}
    assert _docs(monkeypatch, DEMO_REPOS) == ["README.md"]


def test_index_reads_a_single_materials_repo_semester(monkeypatch):
    sections = _index(monkeypatch, MATHS_REPOS)
    got = {s["name"]: [e["name"] for e in s["entries"]] for s in sections}
    # Each top-level directory is its own section here, and `datasets/` needs no ordinal
    # anywhere to appear. The root SYLLABUS.md takes the repo's name.
    #
    # `.github/` shows up, which is the deliberate cost of filtering by a closed list of
    # names rather than by dots: it cannot normally reach a semester repo at all
    # (`deploy.ROOT_RELEASE_EXCLUDED` never releases a root `.github`), so if it is here it
    # was released on purpose and saying so is right. The `.DS_Store` beside it is not -
    # nobody released that, a file manager wrote it.
    assert got == {
        ".github": ["workflows/"],
        "datasets": ["housing.csv"],
        "labs": ["01_lab/"],
        "lectures": ["01_lecture/"],
    }
    # The root files are course documents now, not a section named after the repo.
    assert _docs(monkeypatch, MATHS_REPOS) == ["SYLLABUS.md"]


def test_index_folds_a_directory_to_one_counted_link(monkeypatch):
    lectures = next(
        s for s in _index(monkeypatch, MATHS_REPOS) if s["name"] == "lectures"
    )
    entry = lectures["entries"][0]
    # Never the directory's contents: one of these holds a couple of thousand files.
    assert entry["name"] == "01_lecture/" and entry["files"] == 2
    assert entry["url"].endswith("/tree/main/lectures/01_lecture")
    assert lectures["files"] == 2


def test_index_links_a_file_as_a_blob_and_counts_no_files(monkeypatch):
    datasets = next(
        s for s in _index(monkeypatch, MATHS_REPOS) if s["name"] == "datasets"
    )
    entry = datasets["entries"][0]
    assert entry["url"].endswith("/blob/main/datasets/housing.csv")
    assert "files" not in entry  # a file is not a folder with a count


def test_index_nests_a_directory_instead_of_only_folding_it(monkeypatch):
    # The All Materials tab shows the whole shape of what shipped, not just a count -
    # unlike a session row's links (`_shape_links`), a folded subfolder's contents ARE
    # reachable in the page itself, at any depth.
    lectures = next(
        s for s in _index(monkeypatch, MATHS_REPOS) if s["name"] == "lectures"
    )
    top = lectures["entries"][0]
    assert top["name"] == "01_lecture/"
    nested = {e["name"]: e for e in top["entries"]}
    assert set(nested) == {"deck.html", "media/"}
    assert "entries" not in nested["deck.html"] and "files" not in nested["deck.html"]
    assert nested["deck.html"]["url"].endswith(
        "/blob/main/lectures/01_lecture/deck.html"
    )
    media = nested["media/"]
    assert media["files"] == 1
    assert [e["name"] for e in media["entries"]] == ["img.png"]
    assert media["entries"][0]["url"].endswith(
        "/blob/main/lectures/01_lecture/media/img.png"
    )


def test_index_is_empty_yaml_when_nothing_is_released(monkeypatch):
    monkeypatch.setattr(site, "_repo_tree", lambda o, r: ("main", ()))
    assert yaml.safe_load(
        site._materials_index("Semester-f2026", ["materials"], {})
    ) == {"sections": []}
    # And with no repos at all, without touching the tree.
    assert yaml.safe_load(site._materials_index("Semester-f2026", [], {})) == {
        "sections": []
    }


def test_index_puts_directories_before_files(monkeypatch):
    # Both in ONE section, which needs the ordinal shape: a non-ordinal directory would
    # become a section of its own rather than an entry beside the root file.
    repos = {"m": ("01_zzz/a.txt", "01_zzz/aaa.md")}
    entries = [e["name"] for e in _index(monkeypatch, repos)[0]["entries"]]
    # A directory listing: the structure is what a reader scans first, unlike a session
    # row, which leads with its deliverables.
    assert entries == ["01_zzz/"]


def test_index_gives_a_non_ordinal_directory_its_own_section(monkeypatch):
    # The rule that makes both semester shapes work: an ordinal child means the REPO is the
    # section, a non-ordinal one means the DIRECTORY is.
    repos = {"m": ("handbook/rules.md", "aaa.md")}
    sections = _index(monkeypatch, repos)
    assert {s["name"]: [e["name"] for e in s["entries"]] for s in sections} == {
        "handbook": ["rules.md"]
    }
    # ...and the root file is a course document, not a section named after the repo.
    assert _docs(monkeypatch, repos) == ["aaa.md"]


def test_a_semester_gets_a_tab_per_kind_it_has_rows_of():
    semester = site_repo.theme_pages(semester=True, kinds=["lab", "drop-in"])
    assert "labs.md" in semester and "drop-ins.md" in semester
    assert "lectures.md" not in semester and "readings.md" not in semester
    assert (
        "layout: kind\n" in semester["labs.md"] and "kind: lab\n" in semester["labs.md"]
    )
    assert "permalink: /drop-ins/" in semester["drop-ins.md"]
    assert "title: Drop-ins" in semester["drop-ins.md"]
    assert "All Materials" in semester["materials.md"]
    assert "permalink: /other/" in site_repo.theme_pages(True, ["other"])["other.md"]
    assert "title: Other" in site_repo.theme_pages(True, ["other"])["other.md"]
    # A public course site keeps its own pages: /materials/ is its readings page.
    public = site_repo.theme_pages(semester=False)
    assert "readings.md" not in public
    assert "layout: readings" in public["materials.md"]
    assert "layout: lectures" in public["lectures.md"]


def test_a_tab_with_no_rows_is_retired_only_when_the_sync_wrote_it(tmp_path):
    written = site_repo.theme_pages(
        semester=True, kinds=["lecture", "readings", "exam"]
    )
    for name in ("lectures.md", "readings.md"):
        (tmp_path / name).write_text(written[name])
    # An older sync's page, and one a person made by hand under a tab's name.
    (tmp_path / "labs.md").write_text(
        "---\nlayout: labs\ntitle: Labs\npermalink: /labs/\n---\n"
    )
    (tmp_path / "exams.md").write_text("---\ntitle: Exam rules\n---\nBring a pen.\n")
    assert set(site_repo.retired_kind_pages(["lecture"], tmp_path)) == {
        "readings.md",
        "labs.md",
    }


def test_every_page_states_its_own_access_rule():
    semester = site_repo.theme_pages(semester=True, kinds=["lecture", "readings"])
    # auditors read released materials but get no assignments, so the materials pages
    # name them and the assignments page does not
    assert "enrolled students & auditors." in semester["lectures.md"]
    assert "enrolled students & auditors." in semester["readings.md"]
    assert "only accessible to enrolled students/auditors." in semester["materials.md"]
    assert "only accessible to enrolled students." in semester["assignments.md"]
    assert "auditors" not in semester["assignments.md"]
    # The public open-courseware site publishes the same files on purpose, so it claims no
    # gate anywhere.
    for page in site_repo.theme_pages(semester=False).values():
        assert "enrolled" not in page


def test_the_kinds_data_carries_every_policy_kind_with_its_label_and_colours():
    kinds = yaml.safe_load(site_repo.kinds_yaml())
    assert [k["key"] for k in kinds] == [k["key"] for k in policy.kinds()]
    lab = next(k for k in kinds if k["key"] == "lab")
    assert lab == {
        "key": "lab",
        "label": "Lab",
        "plural": "Labs",
        "colour": "#3c763d",
        "background": "#dff0d8",
        "system": False,
        "tab": "/labs/",
    }
    assert next(k for k in kinds if k["key"] == "term")["tab"] == ""


def test_your_profile_is_the_last_semester_tab():
    # The page is generated, so a site created before this one existed gets BOTH the stub
    # and the tab on its next sync - which is the only way a new tab reaches seven live
    # semesters. Last, because it is a setting rather than course content; and semester-only,
    # because the public open-courseware site has no repo a reader could fork.
    semester = site_repo.theme_pages(semester=True)
    assert "layout: profile" in semester["profile.md"]
    assert "permalink: /profile/" in semester["profile.md"]
    assert "profile.md" not in site_repo.theme_pages(semester=False)
    names = [
        i["name"] for i in yaml.safe_load(site_repo.nav_yaml(semester=True))["items"]
    ]
    assert names[-1] == "Your Profile"
    public = [
        i["name"] for i in yaml.safe_load(site_repo.nav_yaml(semester=False))["items"]
    ]
    assert "Your Profile" not in public


def test_no_nav_tab_can_point_at_a_page_this_site_does_not_get():
    # The tab bar and the pages come from one table, and BOTH syncs generate the nav - so
    # the public site cannot ship a Readings tab pointing at a page only semester sites get.
    for semester in (True, False):
        tabs = {
            i["url"]
            for i in yaml.safe_load(site_repo.nav_yaml(semester=semester))["items"]
        }
        generated = {
            f"/{f.removesuffix('.md')}/"
            for f in site_repo.theme_pages(semester=semester)
        }
        assert generated <= tabs  # every generated page has a tab
        # ...and every remaining tab is one the theme provides rather than generates.
        assert tabs - generated == {"/", "/schedule/"}
    public = {
        i["url"] for i in yaml.safe_load(site_repo.nav_yaml(semester=False))["items"]
    }
    assert "/readings/" not in public  # a semester-only page, so a semester-only tab


def test_nav_order_does_not_depend_on_a_string_tie_break():
    # Assignments used to be pinned to integer position 5, which tied with the fourth
    # generated page - so the tab order came down to comparing "/assignments/" against
    # "/materials/". It now follows the page it belongs behind.
    nav = site_repo.nav_yaml(semester=True, kinds=["readings", "lecture", "lab"])
    names = [i["name"] for i in yaml.safe_load(nav)["items"]]
    # The kind tabs in the policy's order, then Assignments and All Materials.
    assert names[2:5] == ["Lectures", "Labs", "Readings"]
    assert names.index("Assignments") == names.index("Readings") + 1
    assert names.index("All Materials") == names.index("Assignments") + 1


def test_details_keeps_the_paragraphs_of_a_multi_line_objective():
    # Hertie learning objectives run to a paragraph, sometimes two. `_q` folds newlines, so
    # a one-line scalar silently ran them together.
    one = site._details("Sample spaces and Bayes' rule.")
    assert one == 'details: "Sample spaces and Bayes\' rule."\n'
    many = site._details("First paragraph.\n\nSecond paragraph.")
    assert yaml.safe_load(many)["details"] == "First paragraph.\n\nSecond paragraph.\n"
    assert site._details("") == "" and site._details("   ") == ""


def test_an_indented_details_block_nests_under_its_parent_key():
    # The due row is a sub-hash the theme reaches through `map: "due_event"`, so it cannot
    # see the parent's copy and needs its own - which has to be legal YAML two levels in.
    # A uniform `textwrap.indent` shift is all it takes: the `|2` indicator counts from
    # the key's own column, and whitespace-only lines are left alone.
    nested = "due_event:\n" + indent(
        site._details("First paragraph.\n\nSecond."), "    "
    )
    assert (
        yaml.safe_load(nested)["due_event"]["details"]
        == "First paragraph.\n\nSecond.\n"
    )
    assert indent(site._details("One line."), "    ") == '    details: "One line."\n'


def test_a_planned_destination_links_only_where_something_exists(monkeypatch):
    # The path itself cannot exist - that is what "not released" means - so linking it
    # would hand a student a 404. The deepest ancestor that IS there gets the link.
    monkeypatch.setattr(
        site, "_repo_tree", lambda o, r: ("main", ("lectures/01_intro/slides.pdf",))
    )
    live = frozenset({"materials"})
    # The repo exists and holds `lectures/`, but not `lectures/03_week-3` yet.
    got = site._dest_link("C", "materials/lectures/03_week-3", live)
    assert (
        got
        == "[`materials/lectures/03_week-3`](https://github.com/C/materials/tree/main/lectures)"
    )
    # A repo that does not exist yet has nothing to link at all.
    assert site._dest_link("C", "labs/01_lab", live) == "`labs/01_lab`"
    # A repo that exists but is empty links the repo itself.
    monkeypatch.setattr(site, "_repo_tree", lambda o, r: ("main", ()))
    assert site._dest_link("C", "materials/lectures/03", live) == (
        "[`materials/lectures/03`](https://github.com/C/materials)"
    )


# ----------------------------------------------------- finding a released syllabus
def test_no_syllabus_means_no_key_at_all(monkeypatch):
    # The home page shows no line rather than an empty one, so the key must be absent -
    # not present and blank.
    monkeypatch.setattr(
        site, "_repo_tree", lambda o, r: ("main", ("lectures/01/a.md",))
    )
    assert "syllabus" not in yaml.safe_load(
        site._materials_index("C", ["materials"], {})
    )
    with_one = yaml.safe_load(
        site._materials_index("C", ["materials"], {}, syllabus=Link("S.md", "u"))
    )
    assert with_one["syllabus"] == "u"
    # A published syllabus pins the copy that renders: the home page shows ONE link, so
    # unlike a file row there is nowhere to put the GitHub one beside it.
    hosted = yaml.safe_load(
        site._materials_index(
            "C", ["materials"], {}, syllabus=Link("S.html", "u", "https://site/S.html")
        )
    )
    assert hosted["syllabus"] == "https://site/S.html"


def _repos(*names):
    return [repo_row(n) for n in names]


def test_a_renamed_org_fails_the_sync_instead_of_no_opping(monkeypatch):
    # Renaming an org leaves `<old>.github.io` behind, demoted to a project page. The
    # expected site repo is then absent, which used to read as "never opted into a site"
    # - green forever while the published site rotted.
    monkeypatch.setattr(site_repo, "repo_exists", lambda org, name: False)
    monkeypatch.setattr(
        site_repo, "list_org_repos", lambda org: _repos("join", "OLD-NAME.github.io")
    )
    built: list[object] = []
    assert site_repo.sync_site_repo("new-name", lambda wd: built.append(wd)) == 1
    assert built == []


def test_an_org_that_never_had_a_site_is_still_a_quiet_noop(monkeypatch):
    monkeypatch.setattr(site_repo, "repo_exists", lambda org, name: False)
    monkeypatch.setattr(
        site_repo, "list_org_repos", lambda org: _repos("join", ".github")
    )
    assert site_repo.sync_site_repo("new-name", lambda wd: None) == 0


def test_a_failed_repo_listing_is_not_read_as_no_site(monkeypatch):
    monkeypatch.setattr(site_repo, "repo_exists", lambda org, name: False)

    def boom(org):
        raise RuntimeError(f"could not list repos in {org}")

    monkeypatch.setattr(site_repo, "list_org_repos", boom)
    assert site_repo.sync_site_repo("new-name", lambda wd: None) == 1


# ------------------------------------------------------- the publication denylist


def test_the_all_materials_index_hides_what_should_never_have_shipped(monkeypatch):
    # The catch-all index lists everything a release happened to carry, so it was the
    # shortest route from "someone released a folder wholesale" to "the whole class has
    # the answers".
    repos = {
        "labs": (
            "01_lab/lab.ipynb",
            "01_lab/solution/answers.ipynb",
            "01_lab/grading.yml",
            "01_lab/Tests/test_hidden.py",
            ".env.production",
            "README.md",
        )
    }
    got = _parse(monkeypatch, repos)
    assert [d["name"] for d in got["documents"]] == ["README.md"]
    entries = got["sections"][0]["entries"]
    assert [e["name"] for e in entries] == ["01_lab/"]
    assert [e["name"] for e in entries[0]["entries"]] == ["lab.ipynb"]


def test_a_denylisted_file_is_never_linked_from_a_public_page(tmp_path):
    (tmp_path / "deck.html").write_text("slides")
    (tmp_path / "grading.yml").write_text("points: 10")
    (tmp_path / ".env").write_text("KEY=live")
    links = public_site._public_links(tmp_path, "/m/session-1/lectures")
    assert [link.name for link in links] == ["deck.html"]


def test_the_denylist_matches_by_name_at_any_depth_and_ignores_case():
    assert repos.has_denied_component("labs/01_lab/Solution/answers.ipynb")
    assert repos.has_denied_component("tests/test_x.py")
    assert repos.has_denied_component("a/.env.local")
    # ...and does not swallow a file that merely contains a denylisted word.
    assert not repos.has_denied_component("labs/01_lab/solutions-discussion.md")
    assert not repos.has_denied_component("labs/testing-guide.md")
