// The demo semester's public site data as the engine generates it today (hertie-dsl-demo-f2026,
// read 2026-09-24), trimmed to the front matter and a few rows of each kind. Team hashes
// dropped; the instructors are the demo's public cards.

export const ORG = 'hertie-dsl-demo-f2026';
export const SITE = `${ORG}.github.io`;

const HEAD = `# SYSTEM-OWNED - do not edit. Generated by the DSL course sync, which clears and
# rewrites this whole collection on every run.`;

export const FILES: Record<string, string> = {
  '_lectures/session-01.md': `---
${HEAD}
type: lecture
date: 2026-08-04T10:00:00
title: "Session 1"
subtitle: "Deep learning in public policy"
details: "What deep learning is, where it already sits in public-sector decision making."
links:
    - url: https://github.com/${ORG}/materials/blob/main/lectures/01_deep-learning-in-public-policy/Session1_E1394_DL_preLecture.pdf
      view_url: https://${SITE}/files/materials/lectures/01_deep-learning-in-public-policy/Session1_E1394_DL_preLecture.pdf
      name: "Session1_E1394_DL_preLecture.pdf"
      section: "lecture"
    - url: https://github.com/${ORG}/materials/blob/main/lectures/01_deep-learning-in-public-policy/Session1_demo_deck.html
      name: "Session1_demo_deck.html"
      section: "lecture"
---
`,
  '_lectures/lab-03.md': `---
${HEAD}
type: lab
date: 2026-09-21T14:00:00
title: "Lab 3"
links:
    - url: https://github.com/${ORG}/materials/blob/main/labs/03_deep-neural-networks-2/Lab_Session_3.ipynb
      name: "Lab_Session_3.ipynb"
      section: "lab"
---
`,
  '_lectures/session-12.md': `---
${HEAD}
type: lecture
date: 2026-10-20T10:00:00
title: "Session 12"
subtitle: "Tutorial presentations"
details: "Students present their tutorial topic to the group."
unreleased: true
links: []
---
_**Materials for session 12 are not yet released**._
`,
  '_events/01-midterm-exam.md': `---
${HEAD}
type: exam
date: 2026-09-25T10:00:00
title: "Midterm Exam"
---
`,
  '_events/cohort-archived.md': `---
${HEAD}
type: special_event
date: 2027-01-12T09:00:00
hide_time: true
title: "Cohort archived"
details: "This cohort is archived on 2027-01-12: every repository in it becomes read-only."
---
`,
  '_events/term-start.md': `---
${HEAD}
type: term_date
date: 2026-08-04T09:00:00
hide_time: true
title: "Term starts"
---
`,
  '_assignments/02-assignment-2.md': `---
${HEAD}
type: assignment
date: 2026-09-01T14:00:00
title: "Assignment 2"
subtitle: "Classification and evaluation"
submit_shape: "assignment-repo-private"
repo_url: "https://github.com/orgs/${ORG}/repositories?q=assignment-2-"
repo_name: "assignment-2-<your-handle>"
repo_name_is_shape: true
cutoff_sentence: "What is on main at the grading cutoff is what is marked."
late_rule: "10% per day, up to 10 days"
max_points: "25"
due_event:
    type: due
    date: 2026-09-29T23:59:00
    title: "Assignment 2"
    subtitle: "Classification and evaluation"
---
{% raw %}
The brief.
{% endraw %}
`,
  '_assignments/03-assignment-3-project.md': `---
${HEAD}
type: assignment
date: 2026-09-15T14:00:00
title: "Assignment 3 Project"
subtitle: "Group project"
submit_shape: "assignment-repo-private"
repo_name: "assignment-3-project-<your-team>"
repo_name_is_shape: true
late_rule: "10% per day, up to 10 days"
max_points: "50"
team_join_url: "https://github.com/${ORG}/welcome/issues/new/choose"
team_join_cap: "3"
team_join_closes: "26th Oct"
due_event:
    type: due
    date: 2026-10-23T23:59:00
    title: "Assignment 3 Project"
---
`,
  '_assignments/06-assignment-6.md': `---
${HEAD}
type: assignment
date: 2026-09-17T04:35:00
title: "Assignment 6"
subtitle: "Referee reports"
submit_shape: "shared-dropbox-repo"
submit_path: "<your-handle>/"
repo_name: "assignment-6-submissions"
late_rule: "10% per day, up to 10 days"
due_event:
    type: due
    date: 2026-09-20T23:59:00
    title: "Assignment 6"
---
`,
  '_assignments/07-assignment-7.md': `---
${HEAD}
type: assignment
date: 2026-09-17T04:35:00
title: "Assignment 7"
subtitle: "Moodle essay"
submit_shape: "external"
submit_url: "https://moodle.hertie-school.org/mod/assign/view.php?id=424242"
submit_host: "moodle.hertie-school.org"
max_points: "100"
due_event:
    type: due
    date: 2026-09-20T23:59:00
    title: "Assignment 7"
---
`,
  '_assignments/08-assignment-8.md': `---
${HEAD}
type: assignment
date: 2026-11-01T10:00:00
title: "Assignment 8"
handout_pending: true
submit_shape: "assignment-repo-private"
repo_name: "assignment-8-<your-handle>"
due_event:
    type: due
    date: 2026-11-10T23:59:00
    title: "Assignment 8"
---
`,
  '_data/people.yml': `# GENERATED by the DSL course sync - do not edit this file.
instructor:
  name: "Prof. Lynn Kaack, PhD"
instructors:
  - name: "Prof. Lynn Kaack, PhD"
    profile_pic: "https://github.com/LynnKaack.png"
    webpage: "https://www.hertie-school.org/de/research/faculty-and-researchers/profile/person/kaack"
    title: "Assistant Professor of Computer Science and Public Policy"
teaching_assistants:
  - name: "Henry Baker"
    profile_pic: "/_images/pp/henrycgbaker.jpg"
    webpage: "https://www.hertie-school.org/en/who-we-are/profile/person/baker"
    title: "Research Engineer & Data Scientist"
`,
  '_data/late_policy.yml': `policies:
  - You have free 8 late days.
  - Once you have used all 8 late days, the penalty is 10% for each additional late day.`,
  '_data/materials.yml': `syllabus: https://github.com/${ORG}/materials/blob/main/SYLLABUS.md
sections:
  - name: "labs"
    entries:
      - name: "Lab_Session_1.ipynb"
        url: https://github.com/${ORG}/materials/blob/main/labs/01_deep-learning-in-public-policy/Lab_Session_1.ipynb
`,
};

/** A gradebook as `grades.distribute` writes it today, for a made-up handle. */
export const GRADES = `student: octo-student
assignments:
  assignment-2:
    submitted: 29 Sep 21:14
    days_late: '0'
    final_grade: '21'
    score:
      Q1: '9'
      Q2: '12'
    max_points: '25'
    feedback: 'Clear evaluation; the threshold argument needs one more *example*.

      '
  assignment-3-project:
    final_grade: '44'
    max_points: '50'
    team: team-alpha
    team_feedback: A convincing model card.
  assignment-6:
    submitted: 23 Sep 09:01
    days_late: '3'
    penalty: -30%
`;
